### ISSUE TITLE
09 -- Revenge of the Nodes -- Michael Pascuzzi

### ISSUE THREAD

**Issue by gatorpazz** [TheIronYard--Orlando/2015--SUMMER--FEE#118]
- [x] **Yak Shaving**
  - [x] _WIP Issue_ `09 -- Revenge of the Nodes`
    - [x] Link to PR in `USERNAME.github.io`
    - [x] Link to PR in `TheIronYard--Orlando/student-roster`
    - [x] Link to PR in `TIY-Assignments`
  - [x] _WIP Branch_
    - [x] `USERNAME.github.io:journal-week-2`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:09--revenge-of-the-nodes`
  - [x] _WIP Files_
    - `USERNAME.github.io`
      - `journal-week-2.md` (suggested)
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/USERNAME.md` (for someone else)
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
    - `FullWidthTabs/`
      - `index.html`
      - `styles.css`
      - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Brainstorming/Outline
  - [x] 1x :+1: + feedback!
  - [x] 2x :+1: + feedback!
- [x] **Reading CSS**
  - [x] Committed and pushed `about/cascading-style-sheets.md`
  - [x] Read _Learn Layout_!
  - [x] First 2 properties!
  - [x] Up to 5 properties!
  - [x] And then there were 8!
  - [x] All 10 in the bag!
- [x] **Now It's Personal**
  - [x] Updated local `master` from `upstream:master`
  - [x] Resolved conflicts...? WHY!?
  - [x] Created new issue in `student-roster`...
- [x] **Shaving the Night Away**
  - [x] Added `ViewModeSwitch` to the list...
  - [x] ...and gutted them all!
  - [x] Wired them back up again...
  - [x] ...with Google Fonts, too!

**Comment by gatorpazz** [comment]
https://github.com/gatorpazz/gatorpazz.github.io/pull/5

**Comment by gatorpazz** [comment]
This probably wasn't fair... https://github.com/TheIronYard--Orlando/student-roster/pull/26

**Comment by gatorpazz** [comment]
https://github.com/gatorpazz/TIY-Assignments/pull/6

**Comment by al-the-x** [comment]
Well done.

**Comment by al-the-x** [comment]
You're getting along fine, owing to your strong visual learning style, but don't forget that this is cohort-based learning: ensure the other members of your cohort are up-to-speed with your understanding. Don't just coast.

**Comment by al-the-x** [comment]
Please review and close.
