### ISSUE TITLE
09--Revenge-of-the-Nodes--Nick-Pope

### ISSUE THREAD

**Issue by pope410211** [TheIronYard--Orlando/2015--SUMMER--FEE#120]
- [x] **Yak Shaving**
  - [x] _WIP Issue_ `09 -- Revenge of the Nodes`
    - [x] Link to PR in `USERNAME.github.io`
    - [x] Link to PR in `TheIronYard--Orlando/student-roster`
    - [x] Link to PR in `TIY-Assignments`
  - [x] _WIP Branch_
    - [x] `USERNAME.github.io:journal-week-2`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:09--revenge-of-the-nodes`
  - [x] _WIP Files_
    - `USERNAME.github.io`
      - `journal-week-2.md` (suggested)
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/USERNAME.md` (for someone else)
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
    - `FullWidthTabs/`
      - `index.html`
      - `styles.css`
      - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Brainstorming/Outline
  - [x] 1x :+1: + feedback!
  - [ ] 2x :+1: + feedback!
- [ ] **Reading CSS**
  - [x] Committed and pushed `about/cascading-style-sheets.md`
  - [x] Read _Learn Layout_!
  - [x] First 2 properties!
  - [x] Up to 5 properties!
  - [x] And then there were 8!
  - [ ] All 10 in the bag!
- [x] **Now It's Personal**
  - [x] Updated local `master` from `upstream:master`
  - [x] Resolved conflicts...? WHY!?
  - [x] Created new issue in `student-roster`...
- [x] **Shaving the Night Away**
  - [x] Added `ViewModeSwitch` to the list...
  - [x] ...and gutted them all!
  - [x] Wired them back up again...
  - [ ] ...with Google Fonts, too

**Comment by pope410211** [comment]
[**Journal WK2 PR**](https://github.com/pope410211/pope410211.github.io/pull/17)

**Comment by pope410211** [comment]
[**Revenge of the Nodes: Beneath the Code Edition**](https://github.com/pope410211/TIY-Assignments/pull/15)

**Comment by pope410211** [comment]
[**PR 2 correct one**](https://github.com/pope410211/student-roster/pull/7)

[**Now it is PERSONAL**](https://github.com/pope410211/student-roster/pull/6)

**Comment by al-the-x** [comment]
Nicely done, sir.

**Comment by al-the-x** [comment]
Please review and close.
