### ISSUE TITLE
09 -- Revenge of the Nodes -- Ben Griffith

### ISSUE THREAD

**Issue by BFGriffith** [TheIronYard--Orlando/2015--SUMMER--FEE#121]
- [x] **Yak Shaving**
  - [x] _WIP Issue_ `09 -- Revenge of the Nodes`
    - [x] Link to PR in `Epicurean306.github.io`
    - [x] Link to PR in `TheIronYard--Orlando/student-roster`
    - [x] Link to PR in `TIY-Assignments`
  - [x] _WIP Branch_
    - [x] `USERNAME.github.io:journal-week-2`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:09--revenge-of-the-nodes`
  - [x] _WIP Files_
    - `USERNAME.github.io`
      - `journal-week-2.md` (suggested)
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/USERNAME.md` (for someone else)
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
    - `FullWidthTabs/`
      - `index.html`
      - `styles.css`
      - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Brainstorming/Outline
  - [x] 1x :+1: + feedback!
  - [x] 2x :+1: + feedback!
- [x] **Reading CSS**
  - [x] Committed and pushed `about/cascading-style-sheets.md`
  - [x] Read _Learn Layout_!
  - [x] First 2 properties!
  - [x] Up to 5 properties!
  - [x] And then there were 8!
  - [x] All 10 in the bag!
- [x] **Now It's Personal**
  - [x] Updated local `master` from `upstream:master`
  - [x] Resolved conflicts...? WHY!?
  - [x] Created new PR in `student-roster`...
- [x] **Shaving the Night Away**
  - [x] Added `ViewModeSwitch` to the list...
  - [x] ...and gutted them all!
  - [ ] Wired them back up again...
  - [ ] ...with Google Fonts, too!

**Comment by BFGriffith** [comment]
[link to PR in `TheIronYard--Orlando/student-roster`](https://github.com/Epicurean306/student-roster/pull/5)

**Comment by BFGriffith** [comment]
[link to PR for TIY-Assignments WIP branch 09 -- Revenge of the Nodes](https://github.com/Epicurean306/TIY-Assignments/pull/11)

**Comment by BFGriffith** [comment]
[link to PR for Epicurean306.github.io WIP branch journal-week-2](https://github.com/Epicurean306/epicurean306.github.io/pull/3)

**Comment by al-the-x** [comment]
Didn't quite get **Shaving the Night Away** correct, and your Day 1 draft was completed this morning. :disappointed:

**Comment by al-the-x** [comment]
Please review and close.
