### ISSUE TITLE
09 -- Revenge of the Nodes -- Jorge Hernandez

### ISSUE THREAD

**Issue by jorgehjr84** [TheIronYard--Orlando/2015--SUMMER--FEE#122]
- [x] **Yak Shaving**
  - [x] _WIP Issue_ `09 -- Revenge of the Nodes`
    - [x] Link to PR in `USERNAME.github.io`
    - [x] Link to PR in `TheIronYard--Orlando/student-roster`
    - [x] Link to PR in `TIY-Assignments`
  - [x] _WIP Branch_
    - [x] `USERNAME.github.io:journal-week-2`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:09--revenge-of-the-nodes`
  - [ ] _WIP Files_
    - `USERNAME.github.io`
      - `journal-week-2.md` (suggested)
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/USERNAME.md` (for someone else)
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
    - `FullWidthTabs/`
      - `index.html`
      - `styles.css`
      - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Brainstorming/Outline
  - [x] 1x :+1: + feedback!
  - [x] 2x :+1: + feedback!
- [x] **Reading CSS**
  - [x] Committed and pushed `about/cascading-style-sheets.md`
  - [x] Read _Learn Layout_!
  - [x] First 2 properties!
  - [x] Up to 5 properties!
  - [x] And then there were 8!
  - [x] All 10 in the bag!
- [x] **Now It's Personal**
  - [x] Updated local `master` from `upstream:master`
  - [x] Resolved conflicts...? WHY!?
  - [ ] Created new issue in `student-roster`...
- [x] **Shaving the Night Away**
  - [x] Added `ViewModeSwitch` to the list...
  - [x] ...and gutted them all!
  - [ ] Wired them back up again...
  - [ ] ...with Google Fonts, too!

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/jorgehjr84.github.io/pull/12

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/student-roster/pull/3

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/TIY-Assignments/pull/17

**Comment by al-the-x** [comment]
Didn't _quite_ follow the directions for **Shaving the Night Away**:
- There should have been a `scripts.js` and `styles.css` file in _each_ project directory
- "Wiring them up" just meant connecting the _empty_ `scripts.js` and `styles.css` files to the `index.html`

**Comment by al-the-x** [comment]
Sorry, fat fingered that... Didn't mean to give you the red pen. This time.

**Comment by al-the-x** [comment]
Please review and close.
