### ISSUE TITLE
09 -- Revenge of the Nodes -- Melissa Rodriguez

### ISSUE THREAD

**Issue by melrodbos** [TheIronYard--Orlando/2015--SUMMER--FEE#123]
- [x] **Yak Shaving**
  - [x] _WIP Issue_ `09 -- Revenge of the Nodes`
    - [x] Link to PR in `USERNAME.github.io`
    - [x] Link to PR in `TheIronYard--Orlando/student-roster`
    - [x] Link to PR in `TIY-Assignments`
  - [x] _WIP Branch_
    - [x] `USERNAME.github.io:journal-week-2`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:09--revenge-of-the-nodes`
  - [x] _WIP Files_
    - `USERNAME.github.io`
      - `journal-week-2.md` (suggested)
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/USERNAME.md` (for someone else)
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
    - `FullWidthTabs/`
      - `index.html`
      - `styles.css`
      - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Brainstorming/Outline
  - [x] 1x :+1: + feedback!
  - [x] 2x :+1: + feedback!
- [x] **Reading CSS**
  - [x] Committed and pushed `about/cascading-style-sheets.md`
  - [x] Read _Learn Layout_!
  - [x] First 2 properties!
  - [x] Up to 5 properties!
  - [x] And then there were 8!
  - [x] All 10 in the bag!
- [x] **Now It's Personal**
  - [x] Updated local `master` from `upstream:master`
  - [ ] Resolved conflicts...? WHY!?
  - [ ] Created new issue in `student-roster`...
- [x] **Shaving the Night Away**
  - [x] Added `ViewModeSwitch` to the list...
  - [x] ...and gutted them all!
  - [x] Wired them back up again...
  - [ ] ...with Google Fonts, too!

**Comment by melrodbos** [comment]
* [ ] **Yak Shaving**
  * [ ] _WIP Issue_ `09 -- Revenge of the Nodes`
    * [ ] Link to PR in `USERNAME.github.io`
    * [ ] Link to PR in `TheIronYard--Orlando/student-roster`
    * [ ] Link to PR in `TIY-Assignments`
  * [ ] _WIP Branch_
    * [ ] `USERNAME.github.io:journal-week-2`
    * [ ] `student-roster:master`
    * [ ] `TIY-Assignments:09--revenge-of-the-nodes`
  * [ ] _WIP Files_
    * `USERNAME.github.io`
      * `journal-week-2.md` (suggested)
      * `about/cascading-style-sheets.md`
    * `student-roster`
      * `2015-05/FEE/USERNAME.md` (for someone else)
    * `TIY-Assignments`
      * `NestedAccordion/`
        * `index.html`
        * `styles.css`
        * `scripts.js`
      * `ViewModeSwitch/`
        * `index.html`
        * `styles.css`
        * `scripts.js`
     * `FullWidthTabs/`
       * `index.html`
       * `styles.css`
       * `scripts.js`
* [ ] **Journal, Week 2**
  * [ ] Brainstorming/Outline
  * [ ] 1x :+1: + feedback!
  * [ ] 2x :+1: + feedback!
* [ ] **Reading CSS**
  * [ ] Committed and pushed `about/cascading-style-sheets.md`
  * [ ] Read _Learn Layout_!
  * [ ] First 2 properties!
  * [ ] Up to 5 properties!
  * [ ] And then there were 8!
  * [ ] All 10 in the bag!
* [ ] **Now It's Personal**
  * [ ] Updated local `master` from `upstream:master`
  * [ ] Resolved conflicts...? WHY!?
  * [ ] Created new issue in `student-roster`...
* [ ] **Shaving the Night Away**
  * [ ] Added `ViewModeSwitch` to the list...
  * [ ] ...and gutted them all!
  * [ ] Wired them back up again...
  * [ ] ...with Google Fonts, too!

**Comment by melrodbos** [comment]
Journal- Week 2
[Pull Request](https://github.com/melrodbos/melrodbos.github.io/pull/8)

**Comment by melrodbos** [comment]
student-roster

https://github.com/melrodbos/student-roster/pull/3

**Comment by melrodbos** [comment]
TIY-Assignments

**Comment by al-the-x** [comment]
^^^ Flag in the sand?

Easy enough to create a PR by creating the branch, adding a commit (with an empty file) and pushing to Github.

**Comment by melrodbos** [comment]
Well, I was kind of hoping I could catch up before homework was graded. The empty files were in no way intended to be left empty. Lesson learned. :expressionless:

**Comment by al-the-x** [comment]
Please review and close.
