### ISSUE TITLE
09 -- Revenge of the Nodes -- JESSY RIORDAN

### ISSUE THREAD

**Issue by JessyRiordan** [TheIronYard--Orlando/2015--SUMMER--FEE#125]
- [x] **Yak Shaving**
  - [x] _WIP Issue_ `09 -- Revenge of the Nodes`
    - [x] Link to PR in `USERNAME.github.io`
    - [x] Link to PR in `TheIronYard--Orlando/student-roster`
    - [x] Link to PR in `TIY-Assignments`
  - [x] _WIP Branch_
    - [x] `USERNAME.github.io:journal-week-2`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:09--revenge-of-the-nodes`
  - [x] _WIP Files_
    - `USERNAME.github.io`
      - `journal-week-2.md` (suggested)
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/USERNAME.md` (for someone else)
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
    - `FullWidthTabs/`
      - `index.html`
      - `styles.css`
      - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Brainstorming/Outline
  - [x] 1x :+1: + feedback!
  - [x] 2x :+1: + feedback!
- [ ] **Reading CSS**
  - [x] Committed and pushed `about/cascading-style-sheets.md`
  - [x] Read _Learn Layout_!
  - [ ] First 2 properties!
  - [ ] Up to 5 properties!
  - [ ] And then there were 8!
  - [ ] All 10 in the bag!
- [x] **Now It's Personal**
  - [x] Updated local `master` from `upstream:master`
  - [x] Resolved conflicts...? WHY!?
  - [x] Created new issue in `student-roster`...
- [ ] **Shaving the Night Away**
  - [x] Added `ViewModeSwitch` to the list...
  - [x] ...and gutted them all!
  - [ ] Wired them back up again...
  - [ ] ...with Google Fonts, too!

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/jessyriordan.github.io/pull/5

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/TIY-Assignments/pull/16

**Comment by JessyRiordan** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/29

**Comment by al-the-x** [comment]
Looks like you forgot to check off some boxes under "Reading CSS"...

**Comment by al-the-x** [comment]
Please review and close.
