### ISSUE TITLE
10 -- Enter CSS -- Melissa Rodriguez

### ISSUE THREAD

**Issue by melrodbos** [TheIronYard--Orlando/2015--SUMMER--FEE#137]
- [x] **Yak Shaving**
  - _WIP Issue_ `10 -- Enter CSS`
    - Link to PR in `USERNAME.github.io`
    - Link to PR in `student-roster`
    - Link to PR in `TIY-Assignments`
  - _WIP Branch_
    - `USRNAME.github.io:journal-week-2`
    - `student-roster:maser`
    - `TIY-Assignments:10--enter-CSS`
  - _WIP Files_
    - `USERNAME.github.io`
      - your journal entry: `8.md`
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/*.md` :evil_smile:
    - `TIY-Assignments`
      - `NestedAccordion/`, `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Rough draft!
  - [x] :+1: x2!
  - [ ] Extra topics in `parking-lot.md`!
- [x] **Githubbing to Know You**
  - [x] Updated from `upstream:master`
  - [x] Edited _everyone_...
  - [x] Pushed and PR'd (izzat a word?)
  - [x] ZOMG CONFLICTS!
  - [ ] **BEAST MODE** Resolve ALL THE THINGS!
- [x] **Following the Blueprints**
  - [x] Nested Accordion
    - [x] ...is nested!
      - [x] Colors make me feel pretty.
      - [x] Also, need better fonts.
      - [x] We don't need no stinkin' bullets!
      - [x] And look, hovering!
      - [ ] Are those insets right?
    - [x] ...and clicky!
      - [x] jQuery in da HOWSS!
      - [ ] Select those elements!
      - [ ] And make 'em click till you bleed!
  - [ ] View Mode Switch
    - [ ] Just the basics...
      - [ ] "Bubbles, what are you doing?" "Coloring..."
      - [ ] Google Fonts FTW!
      - [ ] That's no button...
      - [ ] Border police: theyr're everywhere!
      - [ ] Look, ma, I got icone!
      - [ ] Gimme back my bullets... Wait.
    - [ ] Grid Mode unlocked!
      - [ ] Center ALL THE TINGS!
      - [ ] Lay them out, side-by-side...
      - [ ] **BEAST MODE** How about a breakpoint?
    - [ ] List Mode unlocked!
      - [ ] Same great image, smaller size!
      - [ ] Lines are the new boxes...
      - [ ] Vertical alignment is hard.
      - [ ] **BEAST MODE** They changed something...
    - [ ] Switch activated!
      - [ ] List mode and grid mode, living together, end times stuff.
      - [ ] Didn't you notice that the icon changed?

**Comment by melrodbos** [comment]
Student Roster
[Pull Request](https://github.com/TheIronYard--Orlando/student-roster/pull/43)

**Comment by melrodbos** [comment]
TIY/Assignments
[Pull Request](https://github.com/melrodbos/TIY-Assignments/pull/15)
Note: I currently have two opened pull requests in my repository. I am confused as the one that I opened from branch 09 has the commits that I wanted for PR from branch 10 and vice versa... :scream:

**Comment by melrodbos** [comment]
Journal-Week 2
[Pull Request](https://github.com/melrodbos/melrodbos.github.io/pull/8)

**Comment by al-the-x** [comment]
Like we discussed, you seem to be missing parts of the Github workflow:
1. Ensure that your local _WIP Branch_ has been pushed to Github.
2. Merge your outstanding PRs, which updates the `master` branch in Github
3. Locally, checkout the `master` branch and use `git fetch` and `git merge` to update to match `origin/master`
4. Create and checkout a new _WIP Branch_ per the new assignment.
5. Edit and commit _at least one file_ and push to Github
6. _Immediately open a PR_ from that branch to `master` in Github
7. Continue working, committing frequently; push your work regularly.

Key Takeaways:
- Only work on _one_ branch at a time
- Always base that branch on `master`
- Always merge your PRs into `master`
- Keep local `master` up-to-date
- Create your PRs _early_ so you don't forget!
- Committing is not the same as pushing.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by melrodbos** [comment]
Thank you very much for your feedback and for always being so helpful. I will be more organized and follow the steps provided in the above comment. Hopefully the million merge conflicts I've created  will considerably decrease and eventually stop from today on... :pray:
