### ISSUE TITLE
FullWidthTabs plan

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#150]
- [ ] sans-serif font
- [ ] text color cornflower blue
- [ ] giant wrapper box that's centered on the page: body, div.container, div.tabs#tabs
- [ ] full-width box that wraps all of the tabs: #tabs > nav, #tabs > nav > ul
  - [ ] TODO: plan this out...
- [ ] full-width box that wraps all of the panels: div.content
- [ ] wrapper with 3 columns, side-by-side, evenly spaced (panel): section[id^="section-"]
- [ ] width of each column proportionate to wrapper
- [ ] spacing between columns is constant
  in each column: div.mediabox
- [ ] image: <img>
  - [ ] at the top
  - [ ] full-width of column
  - [ ] use placeholders
  - [ ] heading <h3>
    - [ ] use placeholder text
    - [ ] left-aligned, allowed to wrap
    - [ ] bold, larger font size than body copy
- [ ] body copy <p>
  - [ ] left-aligned, allowed to wrap

**Comment by al-the-x** [comment]
Shouldn't this be in _your_ repo...
