### ISSUE TITLE
12--The Passion of the CSS--Nick Pope

### ISSUE THREAD

**Issue by pope410211** [TheIronYard--Orlando/2015--SUMMER--FEE#158]
- [x]  **Yak Shaving**  
- WIP Issue: 12 -- The Passion of the CSS
-  _WIP Branch_:
  - [x] `USERNAME.github.io:journal-week-3`
  - [x] `student-roster:master`
  - [x] `TIY-Assignments: 12--the-passion-of-the-css`
  - [x] `TIY-Chessboard: master`
  - _WIP Files_:
    - `USERNAME.github.io`
      - [x] `about/html.md`
    - [x] `reflective-journal.md`
    - [x] `tutorial-journal.md`
  - `student-roster`
    - `2015-05/TEMPLATE.md`
  - `TIY-Assignments`
    - `VerticalTimeline/`
      - [x] `bower.json`
    - `MultiColumnForm/`
      - [x] `bower.json`
  - `TIY-Chessboard`
    - [x] `README.md`
    - [x] `scripts/models.js`
- [ ] **Journal, Week 3**
  - [ ] Outline/Brainstorm - `reflective-journal.md`
  - [ ] Peer reviewed by 2 people
  - [ ] Outline/Brainstorm - `tutorial-journal.md`
  - [ ] Peer reviewed by 2 people
- [ ] **Reading HTML**
  - [ ] Flag in the sand: `about/html.md`
  - [ ] Explain the structure of the tag
  - [ ] Non-word characters of the tag
  - [ ] Review and add tags from HTML5 Boilerplate index.html
- [x] **Student Roster**
  - [x] New category / section to template
  - [x] PR to `TIY--Orlando:master`
- [ ] **The Blueprint to success should not involve Yak Shaving**
  - [x] New folders for `ViewTimeline` and `MultiColumnForm`
  - [x] Initialized bower.json file
  - [ ] **BEAST MODE** Set up index.html using HTML5 Boilerplate
- [ ] **TIY Chessboard**
  - [ ] We've got functions! `initBoard` `move`
  - [ ] And a property! `property`
  - [ ] Working on night `moves`
  - [ ] Catalan Opening
  - [ ] **BEAST MODE** Kasparov v Karpov ('84)

**Comment by pope410211** [comment]
[**TIY-Chessboard**](https://github.com/pope410211/TIY-Chessboard) JavaScript: From Terminal with Love

**Comment by pope410211** [comment]
[**PR STUDENT ROSTER**](https://github.com/TheIronYard--Orlando/student-roster/pull/54)

**Comment by pope410211** [comment]
[**TIY-Assignments**](https://github.com/pope410211/TIY-Assignments/pull/20)

**Comment by pope410211** [comment]
[**Journal WK 3**](https://github.com/pope410211/pope410211.github.io/pull/18)

**Comment by al-the-x** [comment]
Some additional branching in `TIY-Chessboard` was expected...

**Comment by al-the-x** [comment]
Not for _this_ assignment but for the rest.

**Comment by al-the-x** [comment]
Please review and close.
