### ISSUE TITLE
01 -- Right Mindset -- Phillip Creglow

### ISSUE THREAD

**Issue by pcreglow** [TheIronYard--Orlando/2015--SUMMER--FEE#16]
- [x] **Yak Shaving**
  - [x] Create WIP Issue: `01 -- Right Mindset`
  - [x] Create WIP Branch: `USERNAME.github.io:01--right-mindset`
    - [x] Add `README.md`
    - [x] Open Pull Request to `USERNAME.github.io:master`
  - [x] Add link to PR in `USERNAME.github.io` to _WIP Issue_
- [x] **Right Mindset**
  - [x] Create `growth-vs-fixed-mindset.md` in `USERNAME.github.io:01--right-mindset`
  - [x] Research _The Growth Mindset_ by Dr Carol Dweck
  - [x] Outline essay in `growth-vs-fixed-mindset.md` in multiple commits
- [x] **Reading JavaScript**
  - [x] Create `about/javascript.md` in `USERNAME.github.io:01--right-mindset`
  - [x] Explain basic literal types: Null, Boolean, Number, String
  - [x] Explain built-in constants: `undefined`, `NaN`, `Infinity`
- [x] **GitHubbing to Know You**
  - [x] Fork `TheIronYard--Orlando/student-roster`
  - [x] Duplicate `TEMPLATE.md` as `USERNAME.md` using your Github username
  - [x] Fill in your name and avatar _only_
  - [x] Open a Pull Request from your fork to the original
  - [x] Add a link to the PR to your _WIP Issue_

**Comment by pcreglow** [comment]
Yak Shaving PR Link

https://github.com/pcreglow/pcreglow.github.io/pull/2

**Comment by pcreglow** [comment]
GitHubbing to Know You PR Link

https://github.com/TheIronYard--Orlando/student-roster/pull/14

**Comment by al-the-x** [comment]
Please review the feedback that I put on TheIronYard--Orlando/student-roster#8 and correct. Close this issue once you do.

**Comment by pcreglow** [comment]
@al-the-x I corrected the error by adding the file to `2015-5/FEE/` and opened a new pull request. The incorrect pull request has been closed.
