### ISSUE TITLE
12 -- The Passion of the CSS -- Phillip Creglow

### ISSUE THREAD

**Issue by pcreglow** [TheIronYard--Orlando/2015--SUMMER--FEE#160]
- [x] **Yak Shaving**
  - _WIP Issue_: `12 -- The Passion of the CSS`
  -  _WIP Branch_:
    - [x] `USERNAME.github.io:journal-week-3`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:12--passion-of-the-css`
    - [x] `TIY-Chessboard:master`
  - _WIP Files_:
    - `USERNAME.github.io`
      - [x] `about/html.md`
      - [x] `*.md` (reflective journal entry)
      - [x] `*.md` (tutorial journal entry)
    - `student-roster`
      - [x] `2015-05/TEMPLATE.md`
    - `TIY-Assignments`
      - `VerticalTimeline`
        - [x] `bower.json`
      - `MultiColumnForm`
        - [x] `bower.json`
    - `TIY-Chessboard`
      - [x] `scripts/models.js`
- [x] **Journal, Week 3**
  - [x] Rough draft - reflective 
  - [x] Rough draft - tutorial 
  - [x] Both journals peer reviewed by 2 people (2x :+1:s)
  - [ ] Final draft - reflective AND tutorial 
- [x] **Reading HTML**
  - [x] Flag in the sand: `about/html.md`
  - [x] Explain the structure of the tag
  - [ ] Non-word characters of the tag
  - [ ] Review and add tags from HTML5 Boilerplate `index.html`
- [x] **Student Roster**
  - [x] New category / section to template
  - [x] PR to `TIY--Orlando:master`
- [x] **The Blueprint to success should not involve Yak Shaving**
  - [x] New folders for `ViewTimeline` and `MultiColumnForm`
  - [x] Initialized bower.json file
  - [ ] **BEAST MODE** Set up index.html using HTML5 Boilerplate
- [x] **TIY Chessboard**
  - [x] We've got functions! `initBoard` `move`
  - [x] And a property! `property`
  - [x] Working on night `moves`
  - [x] Catalan Opening
  - [ ] **BEAST MODE** Kasparov v Karpov ('84)

**Comment by pcreglow** [comment]
https://github.com/pcreglow/pcreglow.github.io/pull/8

**Comment by pcreglow** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/53

**Comment by pcreglow** [comment]
https://github.com/pcreglow/TIY-Assignments/pull/15

**Comment by al-the-x** [comment]
So @sjoyal's advice was _partially_ correct. Your new commits to `student-roster:patch-1` didn't show up on your old PR... The one that I had already merged. What does that teach you about PRs?

**Comment by al-the-x** [comment]
Please review and close.
