### ISSUE TITLE
12 -- Passion of the CSS -- Michael Staehling

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#161]
- [x] **Yak Shaving**
  - _WIP Issue_: `12 -- The Passion of the CSS`
  -  _WIP Branch_:
    - [x] `USERNAME.github.io:journal-week-3`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:12--passion-of-the-css`
    - [x] `TIY-Chessboard:master`
  - _WIP Files_:
    - `USERNAME.github.io`
      - [x] `about/html.md`
      - [x] `*.md` (reflective journal entry)
      - [x] `*.md` (tutorial journal entry)
    - `student-roster`
      - `2015-05/TEMPLATE.md`
    - `TIY-Assignments`
      - `VerticalTimeline`
        - `bower.json`
      - `MultiColumnForm`
        - `bower.json`
    - `TIY-Chessboard`
      - `scripts/models.js`
- [ ] **Journal, Week 3**
  - [x] Rough draft - reflective 
  - [x] Rough draft - tutorial 
  - [x] Both journals peer reviewed by 2 people (2x :+1:s)
  - [ ] Final draft - reflective AND tutorial 
- [x] **Reading HTML**
  - [x] Flag in the sand: `about/html.md`
  - [x] Explain the structure of the tag
  - [x] Non-word characters of the tag
  - [x] Review and add tags from HTML5 Boilerplate `index.html`
- [x] **Student Roster**
  - [x] New category / section to template
  - [x] PR to `TIY--Orlando:master`
- [ ] **The Blueprint to success should not involve Yak Shaving**
  - [x] New folders for `ViewTimeline` and `MultiColumnForm`
  - [x] Initialized bower.json file
  - [ ] **BEAST MODE** Set up index.html using HTML5 Boilerplate
- [ ] **TIY Chessboard**
  - [x] We've got functions! `initBoard` `move`
  - [ ] And a property! `property`
  - [x] Working on night `moves`
  - [x] Catalan Opening
  - [x] **BEAST MODE** Kasparov v Karpov ('84)

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-Chessboard

**Comment by MStaehling** [comment]
https://github.com/MStaehling/MStaehling.github.io/pull/5

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-assignments/pull/18

**Comment by MStaehling** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/55

**Comment by al-the-x** [comment]
Please review and close.
