### ISSUE TITLE
12 -- The Passon of the CSS -- Kim Mattiko

### ISSUE THREAD

**Issue by kmattiko** [TheIronYard--Orlando/2015--SUMMER--FEE#162]
- [x] **Yak Shaving**
  - _WIP Issue_: `12 -- The Passion of the CSS`
  -  _WIP Branch_:
    - [x] `USERNAME.github.io:journal-week-3`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:12--passion-of-the-css`
    - [x] `TIY-Chessboard:master`
  - _WIP Files_:
    - `USERNAME.github.io`
      - [x] `about/html.md`
      - [x] `*.md` (reflective journal entry)
      - [x] `*.md` (tutorial journal entry)
    - `student-roster`
      - `2015-05/TEMPLATE.md`
    - `TIY-Assignments`
      - `VerticalTimeline`
        - `bower.json`
      - `MultiColumnForm`
        - `bower.json`
    - `TIY-Chessboard`
      - `scripts/models.js`
- [x] **Journal, Week 3**
  - [x] Rough draft - reflective 
  - [x] Rough draft - tutorial 
  - [x] Both journals peer reviewed by 2 people (2x :+1:s)
  - [ ] Final draft - reflective AND tutorial 
- [ ] **Reading HTML**
  - [x] Flag in the sand: `about/html.md`
  - [ ] Explain the structure of the tag
  - [ ] Non-word characters of the tag
  - [ ] Review and add tags from HTML5 Boilerplate `index.html`
- [x] **Student Roster**
  - [x] New category / section to template
  - [x] PR to `TIY--Orlando:master`
- [ ] **The Blueprint to success should not involve Yak Shaving**
  - [x] New folders for `ViewTimeline` and `MultiColumnForm`
  - [ ] Initialized bower.json file
  - [ ] **BEAST MODE** Set up index.html using HTML5 Boilerplate
- [x] **TIY Chessboard**
  - [x] We've got functions! `initBoard` `move`
  - [x] And a property! `property`
  - [x] Working on night `moves`
  - [x] Catalan Opening
  - [ ] **BEAST MODE** Kasparov v Karpov ('84)

**Comment by kmattiko** [comment]
https://github.com/kmattiko/kmattiko.github.io/pull/6

**Comment by kmattiko** [comment]
https://github.com/kmattiko/TIY-Chessboard

**Comment by kmattiko** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/41

**Comment by kmattiko** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/60

**Comment by kmattiko** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/61

**Comment by al-the-x** [comment]
I'm concerned by your confusion on basic JavaScript syntax, Kim. You should definitely spend some time with Code School and CodeCademy to get clear on those fundamentals, even at the expense of the assignment.

**Comment by al-the-x** [comment]
- Missing PR for `TIY-Assignments`

**Comment by al-the-x** [comment]
Please review and close.
