### ISSUE TITLE
12 -- Passion of the CSS -- Ben Griffith

### ISSUE THREAD

**Issue by BFGriffith** [TheIronYard--Orlando/2015--SUMMER--FEE#163]
- [x] **Yak Shaving**
  - _WIP Issue_: `12 -- The Passion of the CSS`
  -  _WIP Branch_:
    - [x] `Epicurean306.github.io:journal-week-3`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:12--passion-of-the-css`
    - [x] `TIY-Chessboard:master`
  - _WIP Files_:
    - `Epicurean306.github.io`
      - [x] `about/html.md`
      - [x] `*.md` (reflective journal entry)
      - [x] `*.md` (tutorial journal entry)
    - `student-roster`
      - `2015-05/TEMPLATE.md`
    - `TIY-Assignments`
      - `VerticalTimeline`
        - `bower.json`
      - `MultiColumnForm`
        - `bower.json`
    - `TIY-Chessboard`
      - `scripts/models.js`
- [x] **Journal, Week 3**
  - [x] Rough draft - reflective 
  - [x] Rough draft - tutorial 
  - [x] Both journals peer reviewed by 2 people (2x :+1:s)
  - [ ] Final draft - reflective AND tutorial 
- [x] **Reading HTML**
  - [x] Flag in the sand: `about/html.md`
  - [ ] Explain the structure of the tag
  - [ ] Non-word characters of the tag
  - [ ] Review and add tags from HTML5 Boilerplate `index.html`
- [x] **Student Roster**
  - [x] New category / section to template
  - [x] PR to `TIY--Orlando:master`
- [x] **The Blueprint to success should not involve Yak Shaving**
  - [x] New folders for `ViewTimeline` and `MultiColumnForm`
  - [x] Initialized bower.json file
  - [ ] **BEAST MODE** Set up index.html using HTML5 Boilerplate
- [x] **TIY Chessboard**
  - [ ] We've got functions! `initBoard` `move`
  - [ ] And a property! `property`
  - [ ] Working on night `moves`
  - [ ] Catalan Opening
  - [ ] **BEAST MODE** Kasparov v Karpov ('84)

**Comment by BFGriffith** [comment]
[link to PR for Epicurean306.github.io WIP branch: journal-week-3](https://github.com/Epicurean306/epicurean306.github.io/pull/4)
[new category / section added to TIY Student Roster template.md](https://github.com/TheIronYard--Orlando/student-roster/pull/58)
[link to PR for TIY-Assignments WIP branch 12--passion-of-the-css](https://github.com/Epicurean306/TIY-Assignments/pull/14)

**Comment by al-the-x** [comment]
Hey, just drop the individual links, as-is, into individual comments. No need to format them.

**Comment by al-the-x** [comment]
When they're in individual comments, they're easier to tap on... ;)

**Comment by al-the-x** [comment]
- No `VerticalTimeline/` in `TIY-Assignments`
- No link to `TIY-Chessboard`

**Comment by al-the-x** [comment]
Please review and close.
