### ISSUE TITLE
17 -- HTMLrats -- Michael Staehling

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#200]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `USERNAME.github.io`
      - [x] reflective journal
      - [x] tutorial journal
    - `TIY-Github`: see below
- [ ] How does the API handle authentication?
  - [ ] Do I need to authenticate?
  - [ ] What can I do with an unauthenticated request?
  - [x] How can I authenticate my request? (3 ways)
  - [ ] How do I ask the API for...
    - [ ] The profile information for a specific user?
  - [ ] The repository listing for a specific user?
  - [ ] The recent, public activity for a specific user?
  - [x] Is there a limit to the number of requests I can make?
    - [x] Is there a way of extending that limit?
    - [x] What happens when I hit the limit?
  - [ ] What if there is a lot of data returned?
    - [ ] How can I ask for more (or less) data from a request?
    - [ ] How do I know that there is more data available?
- [x] repository called TIY-Github tree:
  - [x] api/
    - [x] github/
      - [x] users/
- [x] dist/
- [x] specs/
- [x] src/
  - [x] scss/
  - [x] tests/
- [x] create bower.json and package.json files at the top of the repository (i.e. NOT in src/), and use Yeoman to initialize H5BP and Mocha into src/. Create a .gitignore in dist/ that excludes everything except itself.
- [x] Skitch of my github page
- [x] Fetch Octocat
  - [x] Repo
  - [x] profile

**Comment by MStaehling** [comment]
* [ ] repository called TIY-Github tree:

* [ ] api/
   * [ ] github/
    * [ ] users/
* [ ] dist/
* [ ] specs/
* [ ] src/
    * [ ] scss/
    * [ ] tests/
* [ ] create bower.json and package.json files at the top of the repository (i.e. NOT in src/), and use Yeoman to initialize H5BP and Mocha into src/. Create a .gitignore in dist/ that excludes everything except itself.

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-Github/pull/1

**Comment by MStaehling** [comment]
* [ ] Skitch of my github page
* [ ] Fetch Octocat
    * [ ] Repo
    * [ ] profile

**Comment by MStaehling** [comment]
https://github.com/MStaehling/MStaehling.github.io/pull/6

**Comment by al-the-x** [comment]
Prefer to see these checkboxes in the description...

**Comment by MStaehling** [comment]
the api documentation was very confusing so not completely sure what I've read and haven't read and which of the questions I could and couldn't answer

**Comment by al-the-x** [comment]
- Journal Entries
- Reading APIs
- Specs for TIY-Github
