### ISSUE TITLE
17 -- HTMLrats -- Sean Joyal

### ISSUE THREAD

**Issue by sjoyal** [TheIronYard--Orlando/2015--SUMMER--FEE#201]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `USERNAME.github.io`
      - reflective journal
      - tutorial journal
      - `about/APIs.md`
    - `TIY-Github`: see below
- [ ] **Journal, Week 3**
  - [ ] Reflective Post - rough draft
    - [ ] Peer Review x 2!
  - [ ] Tutorial Post - rough draft
    - [ ] Peer Review x2!
- [x] **Reading Ze API**
  - [ ] Read the whole freaking thing
    - [x] Authentication
      - [x] Authenticate
      - [x] Unauthenticated
      - [x] 3 ways to authenticate a request
    - [x] Ask the API for stuff
      - [x] Profile info -- specific user
      - [x] Repo info -- specific user
      - [x] Recent public activity -- specific user
    - [x] Making requests
      - [x] The limit
      - [x] Extending the limit
      - [x] Hitting the limit
    - [x] Data returned
      - [x] A lot of data?
      - [x] Asking for more or less...
      - [x] Is there more data available? How do I know?
- [ ] **More API**
  - [ ] `Promise` interface
  - [ ] `XmlHttpRequest`
  - [ ] `window.fetch`
  - [ ] `q` docs
- [x] **Github Revolution**
  - [x] new repo: `TIY-Github`
  - [x] This tree has a branch: `yak shaving`
    - api/
      - github/
        - users/
    - dist/
    - specs/
    - src/
      - scss/
      - tests/
  - [x] `bower.json` & `package.json` -- TO THE TOP!!! WOAH OHHHHH! _Twin Shadow_ reference
  - [x] H5BP and mocha in `src/`
  - [x] Ignore everything in `dist/` 'cept for the `.gitignore` itself
  - **SKIIIIITCH**
    - [x] Screen shot and mark up profile page
    - [x] Save to `specs/profile.png`
    - [x] Additional pieces saved as `specs/profile-PROFILEPIECENAME.png`
  - **API Gymnastics**
    - [x] `octocat` profile data
    - [x] `octocat` repo data
    - **BEAST MODE**
      - [ ] Fetch YOUR profile data
      - [ ] Fetch your repo data
  - **Scripts added**
    - [x] `start` and `test` in `package.json`
  - **Install stuff**
    - npm install --global:
      - [x] wiredep
      - [x] node-sass
    - bower install:
      - [x] pure
      - [x] jquery
      - [x] lodash

**Comment by sjoyal** [comment]
https://github.com/sjoyal/TIY-Github/pull/1

**Comment by sjoyal** [comment]
https://github.com/sjoyal/sjoyal.github.io/pull/10

**Comment by al-the-x** [comment]
Please review and close.
