### ISSUE TITLE
17 -- HTMLrats -- Jessy Riordan

### ISSUE THREAD

**Issue by JessyRiordan** [TheIronYard--Orlando/2015--SUMMER--FEE#202]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `USERNAME.github.io`
      - reflective journal
      - tutorial journal
    - `TIY-Github`: 
      - `api/`
        - `github/`
          - `users/`
      - `dist/`
      - `specs/`
      - `src/`
        - `scss/`
        - `tests/`
- [x] **Journal**
  - [x] Reflective - Rough Draft/Outline
  - [x] Tutorial - Rough Draft/Outline
- [ ] **Reading APIs**
  - [ ] How does the API handle authentication?
    - [ ] Do I need to authenticate?
    - [ ] What can I do with an unauthenticated request?
    - [ ] How can I authenticate my request? (3 ways)
  - [ ] How do I ask the API for...
    - [ ] The profile information for a specific user?
    - [ ] The repository listing for a specific user?
    - [ ] The recent, public activity for a specific user?
  - [ ] Is there a limit to the number of requests I can make?
    - [ ] Is there a way of extending that limit?
    - [ ] What happens when I hit the limit?
  - [ ] What if there is a lot of data returned?
    - [ ] How can I ask for more (or less) data from a request?
    - [ ] How do I know that there is more data available?
- [x] **Github Revolution**
  - [x] create repo called `TIY-Github`
  - [x] create branch called `yak-shaving`
  - [x] Use `init` command to create `bower.json` 
  - [x] Use `init` command to create `package.json` 
  - [x] use Yeoman to initialize H5BP and Mocha into `src/` 
  - [x] Create a `.gitignore` in `dist/` that excludes everything except itself.
- [ ] **Skitch this Profile**
  - [ ] screenshot your profile page using Skitch and save it to `specs/profile.png`
  - [ ] Break down the layout into pieces and export them with the `profile-` prefix into `specs/` 
    - [ ] Make lots of these.
- [ ] **API Gymnastics**
  - [x] Fetch the profile data for user octocat and store it in `api/github/users/octocat.json`
  - [x] fetch the repository data and save it to `api/github/users/octocat/repos.json`
  - [ ] Anymore data?
  - [ ] **BEAST MODE**: fetch all that data for yourself, save it in `api/github/users/USERNAME.json` and `api/github/users/USERNAME/`
- [x] **Follow the Script!**
  - [x] Add script definitions to your `package.json`:
    - [x]  for `start` that runs `browser-sync` appropriately
    - [x] for `test` that runs `browser-sync` appropriately
- [x] **Install EVERYTHING...**
  - [x] npm install --global:
    - [x] wiredep
    - [x] node-sass
  - [x] bower install
    - [x] pure
    - [x] jquery
    - [x] lodash

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/TIY-Github/pull/1

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/jessyriordan.github.io/pull/7

**Comment by al-the-x** [comment]
Thanks for being honest about what you did and did not do, but skipping (or failing to allocate time for) the API assignment will hurt you. You don't have to understand it completely, but you should try to get some exposure with it.

**Comment by al-the-x** [comment]
Please review and close.
