### ISSUE TITLE
17 -- HTMLrats -- Ben Griffith

### ISSUE THREAD

**Issue by BFGriffith** [TheIronYard--Orlando/2015--SUMMER--FEE#203]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `Epicurean306.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `Epicurean306.github.io`
      - reflective journal
      - tutorial journal
    - `TIY-Github`: see below

**Comment by BFGriffith** [comment]
https://github.com/Epicurean306/epicurean306.github.io/pull/5

**Comment by BFGriffith** [comment]
https://github.com/Epicurean306/TIY-Github/pull/1

**Comment by al-the-x** [comment]
Hard to grade without any checklists...

**Comment by al-the-x** [comment]
Fat fingered... :(

**Comment by al-the-x** [comment]
Please review and close.
