### ISSUE TITLE
17--HTMLrats--Nick Pope

### ISSUE THREAD

**Issue by pope410211** [TheIronYard--Orlando/2015--SUMMER--FEE#204]
- [ ] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `USERNAME.github.io`
      - reflective journal
      - tutorial journal
    - `TIY-Github`: 
      -  Create REPO
        - [x] `api/`
          - [x] `github/`
            - [x] `users/`
        - [x] `dist/`
        - [x] `specs`
        - [x] `src/`
          - [x] `scss/`
          - [x] `tests/`
      - `init`  files:
        - [x] bower.json
        - [x] package.json
      - Yeoman packages:
        - `src/`
          - [x] YO H5BP
          - [x] YO MOCHA
        - `dist/`
          - [x] `.gitignore`
      - SKITCH Personal Profile:
        - [ ] Create Breakdown of profile
          - [ ] save as `profile-.png`
            - [ ] save to `specs/`
        - [ ] Have a party, invite a ton of skitch breakdowns (at least 4)
      - Work out w/ `API`
        - [ ] fetch `octocat` store it in `api/github/users/octocat.json`
          - [ ] fetch the REPO and store it in `api/github/users/octocat/repos.json`
      - BEAST MODE - see `17--HTMLrats` branch.
    - INSTALLATION:
      - `npm install --global`
        - [x] `wiredep`
        - [x] `node-sass`
      - `bower install`
        - [x] `pure`
        - [x] `jQuery`
        - [x] `lodash`

**Comment by pope410211** [comment]
[**TIY-Github**](https://github.com/pope410211/TIY-Github/pull/1)

**Comment by pope410211** [comment]
[**JOURNAL WK 4**](https://github.com/pope410211/pope410211.github.io/pull/19)

**Comment by al-the-x** [comment]
Time to start thinking some more about those journals...! :D

**Comment by al-the-x** [comment]
Please review and close.
