### ISSUE TITLE
17 -- HTMLrats -- Melissa Rodriguez

### ISSUE THREAD

**Issue by melrodbos** [TheIronYard--Orlando/2015--SUMMER--FEE#205]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats -- Melissa Rodriguez`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    -  [x] `USERNAME.github.io`
      - [ ] reflective journal
      - [ ] tutorial journal
    - [x] `TIY-Github`:
- [x] ### YAK Shaving:
- [x] Just get it done. 
- [x] ### Chode School:
  - [x] Java Script Roadtrip 1
  - [x] Java Script Roadtrip 2
  - [ ] Java Script Roadtrip 3
- [x] ### Chessboard:
  - [ ] Get that jQuery working!
  - [x] Look at the Two-dimensional array (maybe try to work that out)
- [ ] ### Journal, Week 4:
  - [ ] Reflective (Css , HTML)
  - [ ] Tutorial (Atom shortcuts?, :nthchild pseudo element?...)
- [x] **Reading APIs**
- [x] **Github Revolution**
  This week, we're building your Github profile with data from the Github API. You'll need to create a new repository called TIY-Github\* and populate it with the usual **README.md** and **LICENSE** file. Then create a branch called `yak-shaving` that adds the following tree:
- [x] api/
  - [x] github/
  - [x] users/
  - [x] dist/
    - [x] .gitignore 
- [x] specs/
- [x] src/
- [x] scss/
- [x] tests/
- [x] Use your init commands to create `bower.json` and `package.json` files at the top of the repository (i.e. NOT insrc/), and use `Yeoman` to initialize `H5BP` and `Mocha` into `src/`. Create a `.gitignore` in `dist/` that **excludes everything except itself**.
- [x] **Skitch this Profile**
  - [x] Grab a screenshot of your profile page using Skitch and save it to specs/profile.png. 
  - [x] Break down the layout into pieces and export them with the profile- prefix into specs/. 
  - [x] For example, `specs/profile-repositories.png` might be the Repositories section of your profile. 
  - [ ] Make lots of these.
- [x] **API Gymnastics:**
  - [x] Fetch the profile data for user octocat and store it in api/github/users/octocat.json, then fetch the repository data and save it to api/github/users/octocat/repos.json. What other data can you identify in your profile? Can you fetch that data, too?
- [x] **Follow the Script!**
  - [x] Add script definitions to your package.json for start and test that run browser-sync appropriately: watch the right files, start in the right place, etc.
- [x] **npm install --global:**
  - [x] `wiredep`
  - [x] `node-sass`
- [x] **bower install:**
  - [x] `pure`
  - [x] `jquery`
  - [x] `lodash`

**Comment by melrodbos** [comment]
### YAK Shaving:
- [ ] Just get it done. 

### Chode School:
- [ ] Java Script Roadtrip 1
- [ ] Java Script Roadtrip 2
- [ ] Java Script Roadtrip 3

### Chessboard:
- [ ] Get that jQuery working!
- [ ] Look at the Two-dimensional array (maybe try to work that out)

### Journal, Week 4:
- [ ] Reflective (Css , HTML)
- [ ] Tutorial (Atom shortcuts?, :nthchild pseudo element?...)

### Reading APIs

We're going to get very familiar with the Github API this week. Start reading the documentation and answering the following questions:

How does the API handle authentication?
Do I need to authenticate?
What can I do with an unauthenticated request?
How can I authenticate my request? (3 ways)
How do I ask the API for...
The profile information for a specific user?
The repository listing for a specific user?
The recent, public activity for a specific user?
Is there a limit to the number of requests I can make?
Is there a way of extending that limit?
What happens when I hit the limit?
What if there is a lot of data returned?
How can I ask for more (or less) data from a request?
How do I know that there is more data available?

Additionally, you'll want to understand the Promise interface and how XmlHttpRequest works. Even though we'll be using jQuery.ajax in class, the documentation for it is somewhat arcane. You might try reading the docs for thewindow.fetch polyfill and the docs for Q, the easiest-to-understand library out there. There's official documentation for Promise in JavaScript, as well.

### Github Revolution
This week, we're building your Github profile with data from the Github API. You'll need to create a new repository called TIY-Github and populate it with the usual README.md and LICENSE file. Then create a branch called yak-shaving that adds the following tree:

api/
github/
users/
dist/
specs/
src/
scss/
tests/
Use your init commands to create bower.json and package.json files at the top of the repository (i.e. NOT insrc/), and use Yeoman to initialize H5BP and Mocha into src/. Create a .gitignore in dist/ that excludeseverything except itself.

### Skitch this Profile

Grab a screenshot of your profile page using Skitch and save it to specs/profile.png. Break down the layout into pieces and export them with the profile- prefix into specs/. For example, specs/profile-repositories.pngmight be the Repositories section of your profile. Make lots of these.

### API Gymnastics

Fetch the profile data for user octocat and store it in api/github/users/octocat.json, then fetch the repository data and save it to api/github/users/octocat/repos.json. What other data can you identify in your profile? Can you fetch that data, too?

### Follow the Script!
Add script definitions to your package.json for start and test that run browser-sync appropriately: watch the right files, start in the right place, etc.

Install EVERYTHING...
In the interest of saving bandwidth (and time, precious precious time) in the office, install the following:

npm install --global:
wiredep
node-sass
bower install
pure
jquery
lodash

**Comment by al-the-x** [comment]
Links?

**Comment by melrodbos** [comment]
TIY-Github
[Pull Request](https://github.com/melrodbos/TIY-Github/pull/1)

**Comment by melrodbos** [comment]
Chessboard
[Pull Request](https://github.com/melrodbos/TIY-Chessboard/pull/2)

**Comment by al-the-x** [comment]
How about the link to the PR in `USERNAME.github.io`...?

**Comment by melrodbos** [comment]
I didn't include the link to that PR because didn't complete the journal entries until after the due date. I am still working on all my entries and tutorials. Remodeling...
