### ISSUE TITLE
17 -- HTMLrats -- Phillip Creglow

### ISSUE THREAD

**Issue by pcreglow** [TheIronYard--Orlando/2015--SUMMER--FEE#206]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `USERNAME.github.io`
      - reflective journal
      - tutorial journal
    - `TIY-Github`: see below
- [x] **Journal - Week 4**
  - [x] Reflective - Outline/Rough Draft
  - [ ] Peer Review x 2!
  - [ ] Tutorial - Outline/Rough Draft
  - [ ] Peer Review x2!
- [x] **TIY-Github**
  - [x] Create new repo: TIY-Github
  - [x] Branch: yak shaving
  - [x] `api/`
  - [x] `github/`
  - [x] `users/`
  - [x] `dist/`
  - [x] `specs/`
  - [x] `src/`
  - [x] `scss/`
  - [x] `tests/`
  - [x] `bower.json`
  - [x] `package.json` 
  - [x] `src/H5BP` 
  - [x] `src/mocha`
  - [x] `dist/ .gitignore`
- [x] **Skitch (`specs/`)**
  - [x] Profile - screenshot
  - [x] `specs/profile.png`
  - [ ] `specs/profile` additional Skitch specs
- [x] **API Gymnastics**
  - [x] `users/octocat.json` profile data
  - [x] `users/octocat/repo.json` data
- [ ] **BEAST MODE**
  - [ ] Fetch your `username` profile data
  - [ ] Fetch your `username` repo data
- [x] **Scripts**
  - [x] `start` and `test` in `package.json`
- [x] **Install** 
  - _ npm install --global:
  - [x] `wiredep`
  - [x] `node-sass`
  - _ bower install:
  - [x] `pure`
  - [x] `jquery`
  - [x] `lodash`

**Comment by pcreglow** [comment]
https://github.com/pcreglow/TIY-Github/pull/1

**Comment by pcreglow** [comment]
https://github.com/pcreglow/pcreglow.github.io/pull/9

**Comment by al-the-x** [comment]
Great job, as usual, sir. Don't get too hung up on what you've "missed"... You might just need longer or more practice to grasp it. You're doing great.

**Comment by al-the-x** [comment]
Please review and close.
