### ISSUE TITLE
17 -- HTMLrats -- Kim Mattiko

### ISSUE THREAD

**Issue by kmattiko** [TheIronYard--Orlando/2015--SUMMER--FEE#207]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `USERNAME.github.io`
      - reflective journal
      - tutorial journal
    - `TIY-Github`: see below

**Comment by al-the-x** [comment]
How about some links?

**Comment by al-the-x** [comment]
Please review and close.
