### ISSUE TITLE
01 -- Right  Mindset -- Melissa Rodriguez

### ISSUE THREAD

**Issue by melrodbos** [TheIronYard--Orlando/2015--SUMMER--FEE#21]
- [x] **Yak Shaving**
  - [x] Create WIP Issue: `01 -- Right Mindset`
  - [x] Create WIP Branch: `USERNAME.github.io:01--right-mindset`
    - [x] Add `README.md`
    - [x] Open Pull Request to `USERNAME.github.io:master`
  - [x] Add link to PR in `USERNAME.github.io` to _WIP Issue_
- [x] **Right Mindset**
  - [x] Create `growth-vs-fixed-mindset.md` in `USERNAME.github.io:01--right-mindset`
  - [x] Research _The Growth Mindset_ by Dr Carol Dweck
  - [x] Outline essay in `growth-vs-fixed-mindset.md` in multiple commits
- [x] **Reading JavaScript**
  - [x] Create `about/javascript.md` in `USERNAME.github.io:01--right-mindset`
  - [x] Explain basic literal types: Null, Boolean, Number, String
  - [x] Explain built-in constants: `undefined`, `NaN`, `Infinity`
- [x] **GitHubbing to Know You**
  - [x] Fork `TheIronYard--Orlando/student-roster`
  - [x] Duplicate `TEMPLATE.md` as `USERNAME.md` using your Github username
  - [x] Fill in your name and avatar _only_
  - [x] Open a Pull Request from your fork to the original
  - [x] Add a link to the PR to your _WIP Issue_

**Comment by melrodbos** [comment]
https://github.com/melrodbos/melrodbos.github.io/pull/1

**Comment by melrodbos** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/7

**Comment by al-the-x** [comment]
I put some feedback on TheIronYard--Orlando/student-roster#7. Make those corrections to your fork and ping me back _on that PR_. Close this issue to acknowledge.

**Comment by melrodbos** [comment]
File placement correction made. @al-the-x
