### ISSUE TITLE
17 -- HTMLrats--Michael Pascuzzi

### ISSUE THREAD

**Issue by gatorpazz** [TheIronYard--Orlando/2015--SUMMER--FEE#211]
- [x] **Yak Shaving**
  - _WIP Issue_: `17 -- HTMLrats`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-4`
    - `TIY-Github:master`
    - `TIY-Github:yak-shaving`
  - _WIP Files_:
    - `USERNAME.github.io`
      - reflective journal
      - tutorial journal
    - `TIY-Github`: see below
- [x] **Journal, Week 3**
  - [x] Reflective Post - rough draft
  - [x] Peer Review x 2!
  - [x] Tutorial Post - rough draft
  - [x] Peer Review x2!
- [ ] **Reading APIs**
  - [x] Authentication
    - [x] Authenticate
    - [x] Unauthenticated
    - [x] 3 ways to authenticate a request
  - [ ] Ask the API for stuff
    - [ ] Profile info -- specific user
    - [ ] Repo info -- specific user
    - [ ] Recent public activity -- specific user
  - [x] Making requests
    - [x] The limit
    - [x] Extending the limit
    - [x] Hitting the limit
  - [ ] Data returned
    - [ ] A lot of data?
    - [ ] Asking for more or less...
    - [ ] Is there more data available? How do I know?
- [ ] **More API**
  - [ ] Promise interface
  - [ ] XmlHttpRequest
  - [ ] window.fetch
  - [ ] q docs
- [x] **Github Revolution**
  - [x] new repo: TIY-Github
  - [x] This tree has a branch: yak shaving
    - api/
      - github/
        - users/
    - dist/
    - specs/
    - src/
      - scss/
      - tests/
  - [x] bower.json & package.json
  - [x] H5BP and mocha in src/
  - [x] Ignore everything in dist/ except .gitignore
- [x] **Skitch**
  - [x] Screen shot and mark up profile page
  - [x] Save to specs/profile.png
  - [ ] Additional pieces saved as specs/profile-PROFILEPIECENAME.png
- [ ] **API Gymnastics**
  - [ ] octocat profile data
  - [ ] octocat repo data
  - **BEAST MODE**
    - [ ] Fetch YOUR profile data
    - [ ] Fetch your repo data
- [ ] Scripts added
  - [ ] start and test in package.json
- [x] Install stuff
  - [x] npm install --global:
    - [x] wiredep
    - [x] node-sass
  - [x] bower install:
    - [x] pure
    - [x] jquery
    - [x] lodash

**Comment by gatorpazz** [comment]
https://github.com/gatorpazz/gatorpazz.github.io/pull/7

**Comment by al-the-x** [comment]
You didn't get to _everything_ but you put in a good effort on everything. Keep it up.

**Comment by al-the-x** [comment]
Please review and close.
