### ISSUE TITLE
HALFTIME -- Michael Staehling

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#212]
- [ ] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME`
  -  _WIP Branch_:
    - `USERNAME.github.io:remodeling`
    -  `TIY-Assignments:halftime`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `_drafts/`
      - `_posts/`
      - `index.html`
      - `css/main.css`
      - `js/main.js`
      - `bower.json`
      - `package.json`
    - `TIY-Assignments`
      - `FullWidthTabs/`
      - `MultiColumnForm/`
      - `NestedAccordion/`
      - `QuotesRotator/`
      - `VerticalTimeline/`
      - `.gitignore`
      - `package.json`
      - `bower.json`
      - `README.md`
- **HALFTIME Journal**
  - [x] Time for some `remodeling`...
  - [x] Moving day, `_posts`...!
  - [x] You got that `yo h5bp`?
  - [x] Bower and NPM, back in the saddle.
  - [x] Browser? Sync'd.
  - [x] Skitched that layout?
  - [x] Breakpoints?
  - [ ] Made a plan...
  - [ ] Wrote it down...
  - [ ] Broke it up...
- **Blueprints Everywhere!**
  - [x] Burnin' down the house!
  - [x] Yo. H5BP, yo. Hey, yo, H5BP.
  - [x] Skitchers gonna Skitch.
  - [x] Planners gonna plan.
  - [x] Yak shaved.
- **HALFTIME Journal**
  - [x] First feature:
    - [x] Committed and pushed!
    - [x] PR open!
    - [x] PR merged!
  - [ ] Second feature:
    - [x] Committed and pushed!
    - [x] PR open!
    - [ ] PR merged!
  - [ ] **BEAST MODE** Journal entry draft...
- **Blueprints Everywhere!**
  - [x] Project A: created first feature!
  - [ ] Project A: merged first feature!
  - [ ] Project B: created first feature!
  - [ ] Project B: merged first feature!
  - [ ] Project C: created first feature!
  - [ ] Project C: merged first feature!
  - [ ] **BEAST MODE** Started features on _all_ projects!
  - [ ] **BEAST MODE** Merged features on _all_ projects!

**Comment by MStaehling** [comment]
https://github.com/MStaehling/MStaehling.github.io/pull/7

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-assignments/pull/20

**Comment by MStaehling** [comment]
https://github.com/MStaehling/MStaehling.github.io/issues/8

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-assignments/issues/21

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-assignments/issues/22

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-assignments/issues/23

**Comment by al-the-x** [comment]
Rename to just "HALFTIME" and combine with #225, please.

**Comment by MStaehling** [comment]
https://github.com/MStaehling/MStaehling.github.io/pull/12
