### ISSUE TITLE
01 -- Right Mindset -- Michael Staehling

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#22]
- [x] **Yak Shaving**
  - [X] Create WIP Issue: `01 -- Right Mindset`
  - [x] Create WIP Branch: `USERNAME.github.io:01--right-mindset`
    - [x] Add `README.md`
    - [x] Open Pull Request to `USERNAME.github.io:master`
  - [x] Add link to PR in `USERNAME.github.io` to _WIP Issue_
- [x] **Right Mindset**
  - [x] Create `growth-vs-fixed-mindset.md` in `USERNAME.github.io:01--right-mindset`
  - [x] Research _The Growth Mindset_ by Dr Carol Dweck
  - [x] Outline essay in `growth-vs-fixed-mindset.md` in multiple commits
- [x] **Reading JavaScript**
  - [x] Create `about/javascript.md` in `USERNAME.github.io:01--right-mindset`
  - [x] Explain basic literal types: Null, Boolean, Number, String
  - [x] Explain built-in constants: `undefined`, `NaN`, `Infinity`
- [x] **GitHubbing to Know You**
  - [x] Fork `TheIronYard--Orlando/student-roster`
  - [x] Duplicate `TEMPLATE.md` as `USERNAME.md` using your Github username
  - [x] Fill in your name and avatar _only_
  - [x] Open a Pull Request from your fork to the original
  - [x] Add a link to the PR to your _WIP Issue_

**Comment by MStaehling** [comment]
https://github.com/MStaehling/michaelstaehling.github.io/pull/1

**Comment by MStaehling** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/6

**Comment by MStaehling** [comment]
https://github.com/MStaehling/michaelstaehling.github.io

**Comment by al-the-x** [comment]
Please review and close. There's some feedback in your PRs that you should follow, and you should probably come see me about that merge conflict.
