### ISSUE TITLE
19 -- HALFTIME -- Michael Staehling

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#225]
- [ ] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME` (same)
  -  _WIP Branch_:
    - `USERNAME.github.io`
      - `remodeling`
      - `feature/FEATURE-NAME`
    - `TIY-Assignments`
      - `feature/PROJECT-NAME/FEATURE-NAME`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `index.html`
      - `css/main.css`
      - `js/main.js`
    - `TIY-Assignments`
      - `PROJECT-NAME/`
        - `index.html`
        - `css/main.css`
        - `js/main.js`
- **HALFTIME Journal**
  - [ ] First feature:
    - [ ] Committed and pushed!
    - [ ] PR open!
    - [ ] PR merged!
  - [ ] Second feature:
    - [ ] Committed and pushed!
    - [ ] PR open!
    - [ ] PR merged!
  - [ ] **BEAST MODE** Journal entry draft...
- **Blueprints Everywhere!**
  - [ ] Project A: created first feature!
  - [ ] Project A: merged first feature!
  - [ ] Project B: created first feature!
  - [ ] Project B: merged first feature!
  - [ ] Project C: created first feature!
  - [ ] Project C: merged first feature!
  - [ ] **BEAST MODE** Started features on _all_ projects!
  - [ ] **BEAST MODE** Merged features on _all_ projects!

**Comment by al-the-x** [comment]
You should only have _one_ "HALFTIME!" issue...
