### ISSUE TITLE
02 -- Tools on Tuesday -- Nick Pope

### ISSUE THREAD

**Issue by pope410211** [TheIronYard--Orlando/2015--SUMMER--FEE#27]
- [x] **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - [x] `javascript-koans:02--tools-on-tues`
    - [x] `USERNAME.github.io:01--right-mindset` (cont'd)
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io`
      - [x] `growth-vs-fixed-mindset.md`
      - [x] `about/javascript.md`
    - [x] `javascript-koans`
      - [x] `koans/AboutExpects.js`
      - [x] `koans/AboutArrays.js`
      - [x] `koans/AboutFunctions.js`
- [x] **The Right Mindset (cont'd)**
  - [x] added Rough Draft to `growth-vs-fixed-mindset.md`
- [ ] **Reading JavaScript**
  - [x] added 2 more entries
  - [x] added 5 more entries
  - [x] added 10 entries!
  - [x] added 1 "weirdo" operator
  - [ ] added `function`
    - [ ] example function definition
    - [ ] example function invocation
- [x] **JavaScript Koans**
  - [x] forked https://github.com/mrdavidlaing/javascript-koans
  - [x] cloned it locally with `git` or `hub`
  - [x] worked in branch `02--tools-on-tuesday`
  - [x] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [x] opened Pull Request
  - [x] **NORMAL MODE**
    - [x] `AboutExpects.js`
    - [x] `AboutArrays.js`
    - [x] `AboutFunctions.js`
  - [ ] **BEAST MODE**
    - [ ] `AboutObjects.js`
    - [ ] `AboutMutability.js`
    - [ ] `AboutHigherOrderFunctions.js`
  - [ ] **NIGHTMARE MODE** -- ALL KOANS

**Comment by pope410211** [comment]
https://github.com/pope410211/javascript-koans/pull/1

**Comment by pope410211** [comment]
https://github.com/pope410211/pope410211.github.io/tree/01---right-mindset

**Comment by pope410211** [comment]
I was making attempts to use Atom to update 01--right-mindset and created a the following [**_PULL REQ._**](https://github.com/pope410211/pope410211.github.io/pull/10)

**Comment by al-the-x** [comment]
Good work on this, and great job pulling out **BEAST MODE** on that assignment.

**Comment by al-the-x** [comment]
Please review and close.
