### ISSUE TITLE
02 -- Tools on Tuesday -- Kim Mattiko

### ISSUE THREAD

**Issue by kmattiko** [TheIronYard--Orlando/2015--SUMMER--FEE#29]
- **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - `javascript-koans:02--tools-on-tues`
    - `USERNAME.github.io:01--right-mindset` (cont'd)
  - [x] _WIP Files_:
    - `USERNAME.github.io`
      - `growth-vs-fixed-mindset.md`
      - `about/javascript.md`
    - `javascript-koans`
      - `koans/AboutExpects.js`
      - `koans/AboutArrays.js`
      - `koans/AboutFunctions.js`
- [x] **The Right Mindset (cont'd)**
  - [x] added Rough Draft to `growth-vs-fixed-mindset.md`
- [x] **Reading JavaScript**
  - [x] added 2 more entries
  - [x] added 5 more entries
  - [x] added 10 entries!
  - [x] added 1 "weirdo" operator
  - [x] added `function`
    - [x] example function definition
    - [x] example function invocation
- [x] **JavaScript Koans**
  - [x] forked https://github.com/mrdavidlaing/javascript-koans
  - [x] cloned it locally with `git` or `hub`
  - [x] worked in branch `02--tools-on-tuesday`
  - [x] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [x] opened Pull Request
  - [x] **NORMAL MODE**
    - [x] `AboutExpects.js`
    - [x] `AboutArrays.js`
    - [x] `AboutFunctions.js`
  - [ ] **BEAST MODE**
    - [ ] `AboutObjects.js`
    - [ ] `AboutMutability.js`
    - [ ] `AboutHigherOrderFunctions.js`
  - [ ] **NIGHTMARE MODE** -- ALL KOANS

**Comment by kmattiko** [comment]
https://github.com/kmattiko/javascript-koans

**Comment by kmattiko** [comment]
https://github.com/kmattiko/github.io/blob/01----Right-Mindset/growth-vs-fixed-mindset.md

**Comment by al-the-x** [comment]
These links should be to PRs, not files or repos.

**Comment by al-the-x** [comment]
Please review and close.
