### ISSUE TITLE
02 -- Tools on Tuesday -- JESSY RIORDAN

### ISSUE THREAD

**Issue by JessyRiordan** [TheIronYard--Orlando/2015--SUMMER--FEE#30]
- [x] **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - `javascript-koans:02--tools-on-tues`
    - `USERNAME.github.io:01--right-mindset` (cont'd)
  - [x] _WIP Files_:
    - `USERNAME.github.io`
      - `growth-vs-fixed-mindset.md`
      - `about/javascript.md`
    - `javascript-koans`
      - `koans/AboutExpects.js`
      - `koans/AboutArrays.js`
      - `koans/AboutFunctions.js`
- [x] **The Right Mindset (cont'd)**
  - [x] added Rough Draft to `growth-vs-fixed-mindset.md`
- [x] **Reading JavaScript**
  - [x] added 2 more entries
  - [x] added 5 more entries
  - [x] added 10 entries!
  - [ ] added 1 "weirdo" operator
  - [ ] added `function`
    - [ ] example function definition
    - [ ] example function invocation
- [ ] **JavaScript Koans**
  - [x] forked https://github.com/mrdavidlaing/javascript-koans
  - [x] cloned it locally with `git` or `hub`
  - [x] worked in branch `02--tools-on-tuesday`
  - [x] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [x] opened Pull Request
  - [x] **NORMAL MODE**
    - [x] `AboutExpects.js`
    - [x] `AboutArrays.js`
    - [x] `AboutFunctions.js`
  - [x] **BEAST MODE**
    - [x] `AboutObjects.js`
    - [x] `AboutMutability.js`
    - [ ] `AboutHigherOrderFunctions.js`
  - [ ] **NIGHTMARE MODE** -- ALL KOANS

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/javascript-koans/pull/1

**Comment by JessyRiordan** [comment]
- note to self \* having issues with git push

git push origin 02--tools-on-tuesday
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by al-the-x** [comment]
I think you guys resolved your collective pushing issues, correct? Check the remote URL for your `origin` (HINT: `git remote -v`)... Does it say `https://` or `ssh://`...?

**Comment by JessyRiordan** [comment]
Yes this was resolved. Somehow I have the ssh;// and not htps://

**Comment by al-the-x** [comment]
Missing a link to your essay PR.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by JessyRiordan** [comment]
[Essay PR](https://github.com/JessyRiordan/jessyriordan.github.io/pull/1)
