### ISSUE TITLE
02 -- Tools on Tuesday -- Michael Staehling

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#31]
- **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - `javascript-koans:02--tools-on-tues`
    - `USERNAME.github.io:01--right-mindset` (cont'd)
  - [x] _WIP Files_:
    - `USERNAME.github.io`
      - `growth-vs-fixed-mindset.md`
      - `about/javascript.md`
    - `javascript-koans`
      - `koans/AboutExpects.js`
      - `koans/AboutArrays.js`
      - `koans/AboutFunctions.js`
- [x] **The Right Mindset (cont'd)
  - [x] added Rough Draft to `growth-vs-fixed-mindset.md`
- [x] **Reading JavaScript**
  - [x] added 2 more entries
  - [x] added 5 more entries
  - [x] added 10 entries!
  - [x] added 1 "weirdo" operator
  - [x] added `function`
    - [x] example function definition
    - [x] example function invocation
- [x] **JavaScript Koans**
  - [x] forked https://github.com/mrdavidlaing/javascript-koans
  - [x] cloned it locally with `git` or `hub`
  - [x] worked in branch `02--tools-on-tuesday`
  - [x] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [x] opened Pull Request
  - [x] **NORMAL MODE**
    - [x] `AboutExpects.js`
    - [x] `AboutArrays.js`
    - [x] `AboutFunctions.js`
  - [x] **BEAST MODE**
    - [x] `AboutObjects.js`
    - [x] `AboutMutability.js`
    - [x] `AboutHigherOrderFunctions.js`
  - [x] **NIGHTMARE MODE** -- ALL KOANS

**Comment by MStaehling** [comment]
https://github.com/MStaehling/javascript-koans/pull/1

**Comment by MStaehling** [comment]
https://github.com/MStaehling/michaelstaehling.github.io/blob/01--right-mindset/growth-vs-fixed-mindset.md

**Comment by al-the-x** [comment]
Great job on your koans, but I need a link to your PR, not the file inside the branch... You've deleted the branch now, so your link is broken.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by MStaehling** [comment]
https://github.com/MStaehling/michaelstaehling.github.io/pulls
