### ISSUE TITLE
02 -- Tools on Tuesday -- Phillip Creglow

### ISSUE THREAD

**Issue by pcreglow** [TheIronYard--Orlando/2015--SUMMER--FEE#34]
- **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - `javascript-koans:02--tools-on-tues`
    - `USERNAME.github.io:01--right-mindset` (cont'd)
  - [x] _WIP Files_:
    - `USERNAME.github.io`
      - `growth-vs-fixed-mindset.md`
      - `about/javascript.md`
    - `javascript-koans`
      - `koans/AboutExpects.js`
      - `koans/AboutArrays.js`
      - `koans/AboutFunctions.js`
- [x] **The Right Mindset** (cont'd)
  - [x] added Rough Draft to `growth-vs-fixed-mindset.md`
- [x] **Reading JavaScript**
  - [x] added 2 more entries
  - [x] added 5 more entries
  - [x] added 10 entries!
  - [x] added 1 "weirdo" operator
  - [x] added `function`
    - [x] example function definition
    - [x] example function invocation
- [x] **JavaScript Koans**
  - [x] forked https://github.com/mrdavidlaing/javascript-koans
  - [x] cloned it locally with `git` or `hub`
  - [x] worked in branch `02--tools-on-tuesday`
  - [x] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [x] opened Pull Request
  - [x] **NORMAL MODE**
    - [x] `AboutExpects.js`
    - [x] `AboutArrays.js`
    - [x] `AboutFunctions.js`
  - [ ] **BEAST MODE**
    - [ ] `AboutObjects.js`
    - [ ] `AboutMutability.js`
    - [ ] `AboutHigherOrderFunctions.js`
  - [ ] **NIGHTMARE MODE** -- ALL KOANS

**Comment by pcreglow** [comment]
* **Yak Shaving**
  * [ ] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  * [ ] _WIP Branch_:
    * `javascript-koans:02--tools-on-tues`
    * `USERNAME.github.io:01--right-mindset` (cont'd)
  * [ ] _WIP Files_:
    * `USERNAME.github.io`
      * `growth-vs-fixed-mindset.md`
      * `about/javascript.md`
    * `javascript-koans`
      * `koans/AboutExpects.js`
      * `koans/AboutArrays.js`
      * `koans/AboutFunctions.js`
* [ ] **The Right Mindset (cont'd)
  * [ ] added Rough Draft to `growth-vs-fixed-mindset.md`
* [ ] **Reading JavaScript**
  * [ ] added 2 more entries
  * [ ] added 5 more entries
  * [ ] added 10 entries!
  * [ ] added 1 "weirdo" operator
  * [ ] added `function`
    * [ ] example function definition
    * [ ] example function invocation
* [ ] **JavaScript Koans**
  * [ ] forked https://github.com/mrdavidlaing/javascript-koans
  * [ ] cloned it locally with `git` or `hub`
  * [ ] worked in branch `02--tools-on-tuesday`
  * [ ] pushed to Github: `git push origin 02--tools-on-tuesday`
  * [ ] opened Pull Request
  * [ ] **NORMAL MODE**
    * [ ] `AboutExpects.js`
    * [ ] `AboutArrays.js`
    * [ ] `AboutFunctions.js`
  * [ ] **BEAST MODE**
    * [ ] `AboutObjects.js`
    * [ ] `AboutMutability.js`
    * [ ] `AboutHigherOrderFunctions.js`
  * [ ] **NIGHTMARE MODE** -- ALL KOANS

**Comment by pcreglow** [comment]
https://github.com/pcreglow/javascript-koans/tree/02--tools-on-tuesday

**Comment by pcreglow** [comment]
https://github.com/pcreglow/javascript-koans/pull/1

**Comment by pcreglow** [comment]
pcreglow.github.io:01--right-mindset PR

https://github.com/pcreglow/pcreglow.github.io/pull/2

**Comment by al-the-x** [comment]
Looking good. Would like to see a final draft that finishes out your thoughts on the mindsets. I can tell you can write a lot more on the subject.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by pcreglow** [comment]
Final Draft: Growth vs. Fixed Mindset Essay PR

https://github.com/pcreglow/pcreglow.github.io/pull/5
