### ISSUE TITLE
02 -- Tools on Tuesday -- Ben Griffith

### ISSUE THREAD

**Issue by BFGriffith** [TheIronYard--Orlando/2015--SUMMER--FEE#35]
- **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- BEN GRIFFITH`
  - [x] _WIP Branch_:
    - `javascript-koans:02--tools-on-tues`
    - `Epicurean306.github.io:01--right-mindset` (cont'd)
  - [x] _WIP Files_:
    - `Epicurean306.github.io`
      - `growth-vs-fixed-mindset.md`
      - `about/javascript.md`
    - `javascript-koans`
      - `koans/AboutExpects.js`
      - `koans/AboutArrays.js`
      - `koans/AboutFunctions.js`
- [x] **The Right Mindset (cont'd)
  - [x] added Rough Draft to `growth-vs-fixed-mindset.md`
- [x] **Reading JavaScript**
  - [x] added 2 more entries
  - [x] added 5 more entries
  - [x] added 10 entries!
  - [x] added 1 "weirdo" operator
  - [x] added `function`
    - [x] example function definition
    - [x] example function invocation
- [x] **JavaScript Koans**
  - [x] forked https://github.com/mrdavidlaing/javascript-koans
  - [x] cloned it locally with `git` or `hub`
  - [ ] worked in branch `02--tools-on-tuesday`
  - [ ] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [ ] opened Pull Request
  - [ ] **NORMAL MODE**
    - [ ] `AboutExpects.js`
    - [ ] `AboutArrays.js`
    - [ ] `AboutFunctions.js`
  - [ ] **BEAST MODE**
    - [ ] `AboutObjects.js`
    - [ ] `AboutMutability.js`
    - [ ] `AboutHigherOrderFunctions.js`
  - [ ] **NIGHTMARE MODE** -- ALL KOANS

**Comment by BFGriffith** [comment]
https://github.com/Epicurean306/epicurean306.github.io/blob/01--right-mindset/about/javascript.md

https://github.com/Epicurean306/epicurean306.github.io/blob/01--right-mindset/growth-vs-fixed-mindset.md

**Comment by al-the-x** [comment]
Should be links to your PR, not to the files.

**Comment by al-the-x** [comment]
Also missing links to your `javascript-koans` fork.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by BFGriffith** [comment]
Thanks for the feedback. Still trying to learn correct workflows as well as remedial JavaScript... Continuing to work on koans when I have time.
