### ISSUE TITLE
04 --TodoCLI, Part 2 --JESSY RIORDAN

### ISSUE THREAD

**Issue by JessyRiordan** [TheIronYard--Orlando/2015--SUMMER--FEE#54]
-  **Yak Shaving**
  -  [x] _WIP Issue:_ `04 -- TodoCLI, Part 2 -- YOUR NAME`
  - [x] _WIP Branch:_
    - [x] `USERNAME.github.io:04--todo-cli-2`
    - [x] `TIY-Assignments:04--todo-cli-2`
  - [x] _WIP Files:_
    - [x] `USERNAME.github.io`
      - [x] `about/javascript.md`
    - [x] `TIY-Assignments`
      - [x] `todos.js`
      - [x] `string-calculator.js`
      - [x] `check-writing.js`
-  **Reading JavaScript**
  - [ ] `{ }` as block operator
  - [ ] `if`, `else`, `switch`
  - [ ] `try/catch`, `throw`
  - [ ] `for`, `while`, `do-while`
-  **Todo CLI, Part 2**
  - [x] checkpoint from end of class
  - [x] added 1 new (failing) test!
  - [x] passing tests again!
  - [x] added 1 new feature!
  - [ ] **BEAST MODE** API Complete!
  - [ ] **NIGHTMARE MODE** Feature complete!
-  **Coding Katas**
  - [ ] **String Calculator**
    - [x] function `toNumber` exists!
    - [x] `toNumber("zero")` works!
    - [x] function `add` exists!
    - [x] `add("zero", "zero")` works!
    - [x] `"one"` plus `"one"` is `2`!
    - [x] `"two"` plus `"two"` is `4`!
    - [ ] make `"seven"` up yours!
    - [ ] and `"nine"` is the end!
  - [x] First pair!
  - [ ] Second pair!
  - [ ] Third pair!

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/TIY-Assignments/pull/9

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/jessyriordan.github.io/pull/2

**Comment by al-the-x** [comment]
See feedback on your PRs, but otherwise good work! Please help your peers follow the turn-in instructions, particularly about linking their PRs. Several are missing that step.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by JessyRiordan** [comment]
I left comments on my PR's. Also, I am thinking everyone is _starting_ to figure out this whole linking thing! Well I hope so. :smile:
