### ISSUE TITLE
04 -- TodoCLI, Part 2 -- Phillip Creglow

### ISSUE THREAD

**Issue by pcreglow** [TheIronYard--Orlando/2015--SUMMER--FEE#57]
- **Yak Shaving**
  - _WIP Issue:_ `04 -- TodoCLI, Part 2 -- YOUR NAME`
  - _WIP Branch:_
    - `USERNAME.github.io:04--todo-cli-2`
    - `TIY-Assignments:04--todo-cli-2`
  - _WIP Files:_
    - `USERNAME.github.io`
      - `about/javascript.md`
    - `TIY-Assignments`
      - `todos.js`
      - `string-calculator.js`
      - `check-writing.js`
- **Reading JavaScript**
  - [x] `{ }` as block operator
  - [x] `if`, `else`, `switch`
  - [x] `try/catch`, `throw`
  - [x] `for`, `while`, `do-while`
- **Todo CLI, Part 2**
  - [x] checkpoint from end of class
  - [x] added 1 new (failing) test!
  - [x] passing tests again!
  - [x] added 1 new feature!
  - [ ] **BEAST MODE** API Complete!
  - [ ] **NIGHTMARE MODE** Feature complete!
- **Coding Katas**
  - **String Calculator**
    - [x] function `toNumber` exists!
    - [x] `toNumber("zero")` works!
    - [x] function `add` exists!
    - [x] `add("zero", "zero")` works!
    - [x] `"one"` plus `"one"` is `2`!
    - [x] `"two"` plus `"two"` is `4`!
    - [x] make `"seven"` up yours!
    - [x] and `"nine"` is the end!
  - [x] First pair!
  - [x] Second pair!
  - [x] Third pair!

**Comment by pcreglow** [comment]
TIY-Assignments/04--todo-cli-2 PR

https://github.com/pcreglow/TIY-Assignments/pull/8

**Comment by pcreglow** [comment]
pcreglow.github.io/04--todo-cli-2 PR

https://github.com/pcreglow/pcreglow.github.io/pull/5

**Comment by al-the-x** [comment]
Please review and close.
