### ISSUE TITLE
04 -- TodoCLI, Part 2 -- Ben Griffith

### ISSUE THREAD

**Issue by BFGriffith** [TheIronYard--Orlando/2015--SUMMER--FEE#58]
- **Yak Shaving**
  - _WIP Issue:_ `04 -- TodoCLI, Part 2 -- YOUR NAME`
  - _WIP Branch:_
    - `USERNAME.github.io:04--todo-cli-2`
    - `TIY-Assignments:04--todo-cli-2`
  - _WIP Files:_
    - `USERNAME.github.io`
      - `about/javascript.md`
    - `TIY-Assignments`
      - `todos.js`
      - `string-calculator.js`
      - `check-writing.js`
- **Reading JavaScript**
  - [ ] `{ }` as block operator
  - [ ] `if`, `else`, `switch`
  - [ ] `try/catch`, `throw`
  - [ ] `for`, `while`, `do-while`
- **Todo CLI, Part 2**
  - [x] checkpoint from end of class
  - [x] added 1 new (failing) test!
  - [ ] passing tests again!
  - [ ] added 1 new feature!
  - [ ] **BEAST MODE** API Complete!
  - [ ] **NIGHTMARE MODE** Feature complete!
- **Coding Katas**
  - **String Calculator**
    - [x] function `toNumber` exists!
    - [ ] `toNumber("zero")` works!
    - [x] function `add` exists!
    - [ ] `add("zero", "zero")` works!
    - [x] `"one"` plus `"one"` is `2`!
    - [x] `"two"` plus `"two"` is `4`!
    - [ ] make `"seven"` up yours!
    - [ ] and `"nine"` is the end!
  - [x] First pair!
  - [x] Second pair!
  - [x] Third pair!

**Comment by al-the-x** [comment]
No links to your PRs! Please include links to _every_ PR you have open in your _WIP Issue_ so that I can provide feedback on them! That's part of the turn-in instructions for _every_ assignment!

**Comment by al-the-x** [comment]
Please review and close.
