### ISSUE TITLE
04 -- TodoCLI, Part 2 -- Sean Joyal

### ISSUE THREAD

**Issue by sjoyal** [TheIronYard--Orlando/2015--SUMMER--FEE#59]
- **Yak Shaving**
  - _WIP Issue:_ `04 -- TodoCLI, Part 2 -- YOUR NAME`
    - [x] Link to PR in `USERNAME.github.io`
    - [x] Link to PR in `TIY-Assignments`
  - _WIP Branch:_
    - `USERNAME.github.io:04--todo-cli-2`
    - `TIY-Assignments:04--todo-cli-2`
  - _WIP Files:_
    - `USERNAME.github.io`
      - [ ] `about/javascript.md`
    - `TIY-Assignments`
      - [x] `todos.js`
      - [x] `string-calculator.js`
      - [x] `check-writing.js`
- **Reading JavaScript**
  - [x] `{ }` as block operator
  - [x] `if`, `else`, `switch`
  - [ ] `try/catch`, `throw`
  - [ ] `for`, `while`, `do-while`
- **Todo CLI, Part 2**
  - [x] checkpoint from end of class
  - [x] added 1 new (failing) test!
  - [x] passing tests again!
  - [x] added 1 new feature!
  - [ ] **BEAST MODE** API Complete!
  - [ ] **NIGHTMARE MODE** Feature complete!
- **Coding Katas**
  - **String Calculator**
    - [x] function `toNumber` exists!
    - [x] `toNumber("zero")` works!
    - [x] function `add` exists!
    - [x] `add("zero", "zero")` works!
    - [x] `"one"` plus `"one"` is `2`!
    - [x] `"two"` plus `"two"` is `4`!
    - [x] make `"seven"` up yours!
    - [x] and `"nine"` is the end!
  - [x] First pair!
  - [x] Second pair!
  - [x] Third pair!

**Comment by sjoyal** [comment]
https://github.com/sjoyal/sjoyal.github.io/pull/3

**Comment by sjoyal** [comment]
https://github.com/sjoyal/TIY-Assignments/pulls

**Comment by al-the-x** [comment]
Gimme a link to the PR I need to look at, not your list of open PRs.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by sjoyal** [comment]
https://github.com/sjoyal/TIY-Assignments/pull/9 @al-the-x
