### ISSUE TITLE
04 -- TodoCLI, Part 2 -- Melissa Rodriguez

### ISSUE THREAD

**Issue by melrodbos** [TheIronYard--Orlando/2015--SUMMER--FEE#60]
- **Yak Shaving**
  - _WIP Issue:_ `04 -- TodoCLI, Part 2 -- YOUR NAME`
  - _WIP Branch:_
    - `USERNAME.github.io:04--todo-cli-2`
    - `TIY-Assignments:04--todo-cli-2`
  - _WIP Files:_
    - `USERNAME.github.io`
      - `about/javascript.md`
    - `TIY-Assignments`
      - `todos.js`
      - `string-calculator.js`
      - `check-writing.js`
- **Reading JavaScript**
  - [x] `{ }` as block operator
  - [x] `if`, `else`, `switch`
  - [ ] `try/catch`, `throw`
  - [ ] `for`, `while`, `do-while`
- **Todo CLI, Part 2**
  - [x] checkpoint from end of class
  - [x] added 1 new (failing) test!
  - [x] passing tests again!
  - [ ] added 1 new feature!
  - [ ] **BEAST MODE** API Complete!
  - [ ] **NIGHTMARE MODE** Feature complete!
- **Coding Katas**
  - **String Calculator**
    - [x] function `toNumber` exists!
    - [x] `toNumber("zero")` works!
    - [x] function `add` exists!
    - [x] `add("zero", "zero")` works!
    - [x] `"one"` plus `"one"` is `2`!
    - [x] `"two"` plus `"two"` is `4`!
    - [x] make `"seven"` up yours!
    - [x] and `"nine"` is the end!
  - [x] First pair!
  - [x] Second pair!
  - [ ] Third pair!

**Comment by al-the-x** [comment]
No links to your PRs, which is _always_ part of the turn-in instructions. Please provide links to your PRs so that I can provide feedback on your work!

**Comment by al-the-x** [comment]
Please review and close.

**Comment by melrodbos** [comment]
Not again! I apologize. 
Here is one:
[JavaScript Definitions](https://github.com/melrodbos/melrodbos.github.io/pull/6)

Note: I just realized that I have been doing the pull requests, the commits and updates in the wrong branches creating conflict with my work in my local repositories. I am working on fixing that. :scream:

**Comment by melrodbos** [comment]
[Fixed vs. Growth Mindset](https://github.com/melrodbos/melrodbos.github.io/pull/7)
Note: The link is for a pull request of the updated essay but in a different branch. Now I understand where everything is supposed to go. (I think)
