### ISSUE TITLE
04 --TodoCLI, Part 2 -- Nick Pope

### ISSUE THREAD

**Issue by pope410211** [TheIronYard--Orlando/2015--SUMMER--FEE#61]
- **Yak Shaving**
  - _WIP Issue:_ `04 -- TodoCLI, Part 2 -- YOUR NAME`
  - _WIP Branch:_
    - `USERNAME.github.io:04--todo-cli-2`
    - `TIY-Assignments:04--todo-cli-2`
  - _WIP Files:_
    - `USERNAME.github.io`
      - `about/javascript.md`
    - `TIY-Assignments`
      - `todos.js`
      - `string-calculator.js`
      - `check-writing.js`
- **Reading JavaScript**
  - [ ] `{ }` as block operator
  - [ ] `if`, `else`, `switch`
  - [ ] `try/catch`, `throw`
  - [ ] `for`, `while`, `do-while`
- **Todo CLI, Part 2**
  - [x] checkpoint from end of class
  - [x] added 1 new (failing) test!
  - [ ] passing tests again!
  - [ ] added 1 new feature!
  - [ ] **BEAST MODE** API Complete!
  - [ ] **NIGHTMARE MODE** Feature complete!
- **Coding Katas**
  - **String Calculator**
    - [x] function `toNumber` exists!
    - [x] `toNumber("zero")` works!
    - [x] function `add` exists!
    - [x] `add("zero", "zero")` works!
    - [x] `"one"` plus `"one"` is `2`!
    - [x] `"two"` plus `"two"` is `4`!
    - [x] make `"seven"` up yours!
    - [x] and `"nine"` is the end!
  - [x] First pair!
  - [x] Second pair!
  - [ ] Third pair!

**Comment by pope410211** [comment]
[PR for 04--todo-cli-2 : Enjoying some Java](https://github.com/pope410211/TIY-Assignments/pull/9)

**Comment by al-the-x** [comment]
No link to your PR for your journal / reading homework. I know you _did_ them, but I need you to _link_ them.

**Comment by al-the-x** [comment]
Please review and close.
