### ISSUE TITLE
05 -- Monday Review & Preview -- Nick Pope

### ISSUE THREAD

**Issue by pope410211** [TheIronYard--Orlando/2015--SUMMER--FEE#67]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Monday Review & Preview -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
    - [x] link to PR for `TIY-Assignments:05--monday-review+preview`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-1`
    - `TheIronYard--Orlando/student-roster:master`
    - `TIY-Assignments:05--monday-review+preview`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/jquery.md`
      - `journal-week-1.md`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/FEE/`
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `FullWidthTabs/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `QuotesRotator/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [ ] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [ ] created new file named `journal-week-1.md`
  - [ ] commited, pushed, and opened PR to `master`
  - [ ] added draft journal entry
- [ ] **GitHubbing to Know You, Part 2** (due Thu)
  - [ ] merged upstream additions from `TheIronYard/student-roster:master`
  - [ ] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"
- [ ] **Making Blueprints**
  - [x] created branch in `TIY-Assignments` named `05--monday-review+preview`
  - [x] created directories named `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
  - [x] pasted result of `add`-ing empty directories into _WIP Issue_
  - [x] added files: `index.html`, `styles.css`, `scripts.js`
  - [x] copied contents of `index.html` and `styles.css` from examples
  - [ ] **BEAST MODE** working code in the browser!
- [ ] **Prep for TodoMVC**
  - [x] downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template)
  - [x] pushed into `TIY-TodoMVC`
  - [ ] **BEAST MODE** hey, it works!

**Comment by pope410211** [comment]
After creating an empty directory - it will not change red or green and add to the git status and you will not be able to push to origin. My theory is that it is because the Directory is a path, not a file. Info to back my theory is located [**_HERE_**](http://ruby.about.com/od/git/f/Can-I-Add-Empty-Directories-To-Git-Repositories.htm)

**Comment by pope410211** [comment]
After creating files inside the original directory, I was given an option to `git add` and `git commit` then `git push` to create empty files inside a directory and it showed on github. See them [**_HERE_**](https://github.com/pope410211/TIY-Assignments/tree/05--monday-review%2Bpreview/NestedAccordion)

**Comment by pope410211** [comment]
Resources
[**_Blue Print Articles on Tympanus.net_**](http://tympanus.net/codrops/category/blueprints/)
[Nested Accordion](http://tympanus.net/Blueprints/NestedAccordion/)
[Full Width Tabs](http://tympanus.net/Blueprints/FullWidthTabs/)
[Quotes Rotator](http://tympanus.net/Blueprints/QuotesRotator/)

**Comment by pope410211** [comment]
[CLICK HERE](https://github.com/pope410211/TIY-Assignments/pull/10)
 for PR link for Blueprints
**_05--Monday Review & Preview_**

**Comment by pope410211** [comment]
[TIY-Student-Roster PR](https://github.com/pope410211/student-roster/pull/2)

**Comment by pope410211** [comment]
[JOURNAL-Week-1](https://github.com/pope410211/pope410211.github.io/pull/16)

**Comment by pope410211** [comment]
[TODO MVC](https://github.com/pope410211/TIY-TodoMVC)

**Comment by al-the-x** [comment]
Thanks for the link to your `TIY-TodoMVC` repo. On that: don't add and commit `node_modules` and avoid `git add .` if you know what's good for you...

**Comment by al-the-x** [comment]
Please review and close.
