### ISSUE TITLE
05 -- Monday Review & Preview -- Michael Pascuzzi

### ISSUE THREAD

**Issue by gatorpazz** [TheIronYard--Orlando/2015--SUMMER--FEE#68]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Monday Review & Preview -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
    - [x] link to PR for `TIY-Assignments:05--monday-review+preview`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-1`
    - `TheIronYard--Orlando/student-roster:master`
    - `TIY-Assignments:05--monday-review+preview`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `journal-week-1.md`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/FEE/`
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `FullWidthTabs/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `QuotesRotator/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [x] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
- [ ] **GitHubbing to Know You, Part 2** (due Thu)
  - [ ] merged upstream additions from `TheIronYard/student-roster:master`
  - [ ] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"
- [x] **Making Blueprints**
  - [x] created branch in `TIY-Assignments` named `05--monday-review+preview`
  - [x] created directories named `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
  - [x] pasted result of `add`-ing empty directories into _WIP Issue_
  - [x] added files: `index.html`, `styles.css`, `scripts.js`
  - [x] copied contents of `index.html` and `styles.css` from examples
  - [ ] **BEAST MODE** working code in the browser!
- [x] **Prep for TodoMVC**
  - [x] downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template)
  - [x] pushed into `TIY-TodoMVC`
  - [ ] **BEAST MODE** hey, it works!

**Comment by gatorpazz** [comment]
https://github.com/gatorpazz/gatorpazz.github.io/pull/4

**Comment by gatorpazz** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/26

**Comment by gatorpazz** [comment]
Github doesn't allow for the adding of empty directories, only files, I'll admit this is confusing to me and need some clarification in class

**Comment by gatorpazz** [comment]
https://github.com/gatorpazz/TIY-Assignments/pull/4

**Comment by al-the-x** [comment]
Your link to `student-roster` isn't technically a PR, but I also didn't drop the assignments until Tuesday, so I'll overlook that... this time.

**Comment by al-the-x** [comment]
Please review and close.
