### ISSUE TITLE
05 -- Monday Review & Preview -- Sean Joyal

### ISSUE THREAD

**Issue by sjoyal** [TheIronYard--Orlando/2015--SUMMER--FEE#69]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Monday Review & Preview -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
    - [x] link to PR for `TIY-Assignments:05--monday-review+preview`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-1`
    - `TheIronYard--Orlando/student-roster:master`
    - `TIY-Assignments:05--monday-review+preview`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/jquery.md`
      - `journal-week-1.md`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/FEE/`
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `FullWidthTabs/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `QuotesRotator/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [x] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
- [ ] **GitHubbing to Know You, Part 2** (due Thu)
  - [x] merged upstream additions from `TheIronYard/student-roster:master`
  - [ ] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"
- [ ] **Making Blueprints**
  - [x] created branch in `TIY-Assignments` named `05--monday-review+preview`
  - [x] created directories named `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
  - [x] pasted result of `add`-ing empty directories into _WIP Issue_
  - [x] added files: `index.html`, `styles.css`, `scripts.js`
  - [x] copied contents of `index.html` and `styles.css` from examples
  - [ ] **BEAST MODE** working code in the browser!
- [ ] **Prep for TodoMVC**
  - [x] downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template)
  - [x] pushed into `TIY-TodoMVC`
  - [ ] **BEAST MODE** hey, it works!

**Comment by sjoyal** [comment]
Received the following statement in terminal after attempting to add `NestedAccordion`,`FullWidthTabs`, and `QuotesRotator`:

`nothing added to commit but untracked files present (use "git add" to track)`

Google fu returned the following a StackOverflow [question and answer](http://stackoverflow.com/questions/14541253/commit-empty-folder-structure-with-git) explaining that git does not push directories, only files. At the minimum a placeholder file must be included in the directory before pushing to remote.

After creating the empty html, js, and css files in each directory and running git status, I was allowed to add each file, commit and push to GitHub.

**Comment by sjoyal** [comment]
https://github.com/sjoyal/sjoyal.github.io/pull/5

**Comment by sjoyal** [comment]
https://github.com/sjoyal/TIY-Assignments/pull/10

**Comment by sjoyal** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/16

**Comment by al-the-x** [comment]
Sorry, fat fingered that on the train. While you PR in `TIY-Assignments` contains the file changes that I would expect for this assignment, it also has a _lot more_... Probably a `git branch` slip up.

**Comment by al-the-x** [comment]
Please review and close.
