### ISSUE TITLE
05 -- Monday Review & Preview -- JESSY RIORDAN

### ISSUE THREAD

**Issue by JessyRiordan** [TheIronYard--Orlando/2015--SUMMER--FEE#70]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Monday Review & Preview -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
    - [x] link to PR for `TIY-Assignments:05--monday-review+preview`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-1`
    - `TheIronYard--Orlando/student-roster:master`
    - `TIY-Assignments:05--monday-review+preview`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/jquery.md`
      - `journal-week-1.md`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/FEE/`
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `FullWidthTabs/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `QuotesRotator/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [x] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
- [ ] **GitHubbing to Know You, Part 2** (due Thu)
  - [ ] merged upstream additions from `TheIronYard/student-roster:master`
  - [ ] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"
- [ ] **Making Blueprints**
  - [x] created branch in `TIY-Assignments` named `05--monday-review+preview`
  - [x] created directories named `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
  - [x] pasted result of `add`-ing empty directories into _WIP Issue_
  - [x] added files: `index.html`, `styles.css`, `scripts.js`
  - [x] copied contents of `index.html` and `styles.css` from examples
  - [ ] **BEAST MODE** working code in the browser!
- [ ] **Prep for TodoMVC**
  - [x] downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template)
  - [x] pushed into `TIY-TodoMVC`
  - [ ] **BEAST MODE** hey, it works!

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/jessyriordan.github.io/pull/4

**Comment by JessyRiordan** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/3

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/TIY-Assignments/pull/10

**Comment by JessyRiordan** [comment]
Added directories (using terminal) and typed git status, got this:

Jessy at Hakuna-Matata in ~/TIY/TIY-Assignments (05--monday-review+preview)
$ mkdir NestedAccordion

Jessy at Hakuna-Matata in ~/TIY/TIY-Assignments (05--monday-review+preview)
$ mkdir FullWidthTabs

Jessy at Hakuna-Matata in ~/TIY/TIY-Assignments (05--monday-review+preview)
$ mkdir QuotesRotator

Jessy at Hakuna-Matata in ~/TIY/TIY-Assignments (05--monday-review+preview)
$ git status
On branch 05--monday-review+preview
nothing to commit, working directory clean

**Comment by al-the-x** [comment]
Please review and close.
