### ISSUE TITLE
05--Monday review and preview -- Jorge Hernandez

### ISSUE THREAD

**Issue by jorgehjr84** [TheIronYard--Orlando/2015--SUMMER--FEE#74]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Monday Review & Preview -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [ ] link to PR for `TheIronYard--Orlando/student-roster:master`
    - [x] link to PR for `TIY-Assignments:05--monday-review+preview`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-1`
    - `TheIronYard--Orlando/student-roster:master`
    - `TIY-Assignments:05--monday-review+preview`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/jquery.md`
      - `journal-week-1.md`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/FEE/`
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `FullWidthTabs/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `QuotesRotator/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [x] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
- [x] **GitHubbing to Know You, Part 2** (due Thu)
  - [x] merged upstream additions from `TheIronYard/student-roster:master`
  - [ ] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"
- [x] **Making Blueprints**
  - [x] created branch in `TIY-Assignments` named `05--monday-review+preview`
  - [x] created directories named `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
  - [x] pasted result of `add`-ing empty directories into _WIP Issue_
  - [x] added files: `index.html`, `styles.css`, `scripts.js`
  - [x] copied contents of `index.html` and `styles.css` from examples
  - [ ] **BEAST MODE** working code in the browser!
- [ ] **Prep for TodoMVC**
  - [x] downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template)
  - [x] pushed into `TIY-TodoMVC`
  - [ ] **BEAST MODE** hey, it works!

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/jorgehjr84.github.io/pull/9

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/jorgehjr84.github.io/pull/10

**Comment by jorgehjr84** [comment]
https://github.com/jorgehjr84/TIY-Assignments/pull/11

**Comment by jorgehjr84** [comment]
Trying to push empty directories....
I was not able to push the empty directories because apparently you cannot commit empty folders, only files.

**Comment by al-the-x** [comment]
Sorry, but I gotta downgrade this one. I forgot to check for your PR in `student-roster`... Which you didn't link here.

**Comment by al-the-x** [comment]
Reminded after looking at a few of these that I didn't hand out the student roster assignments until Tuesday, so I'll grade a little more leniently.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by jorgehjr84** [comment]
:+1: 

Thanks for the feedback
