### ISSUE TITLE
05 -- Monday Review & Preview -- Phillip Creglow

### ISSUE THREAD

**Issue by pcreglow** [TheIronYard--Orlando/2015--SUMMER--FEE#75]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Monday Review & Preview -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
    - [x] link to PR for `TIY-Assignments:05--monday-review+preview`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-1`
    - `TheIronYard--Orlando/student-roster:master`
    - `TIY-Assignments:05--monday-review+preview`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/jquery.md`
      - `journal-week-1.md`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/FEE/`
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `FullWidthTabs/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `QuotesRotator/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [x] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
- [ ] **GitHubbing to Know You, Part 2** (due Thu)
  - [x] merged upstream additions from `TheIronYard/student-roster:master`
  - [x] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"
- [x] **Making Blueprints**
  - [x] created branch in `TIY-Assignments` named `05--monday-review+preview`
  - [x] created directories named `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
  - [x] pasted result of `add`-ing empty directories into _WIP Issue_
  - [x] added files: `index.html`, `styles.css`, `scripts.js`
  - [x] copied contents of `index.html` and `styles.css` from examples
  - [ ] **BEAST MODE** working code in the browser!
- [x] **Prep for TodoMVC**
  - [x] downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template)
  - [x] pushed into `TIY-TodoMVC`
  - [ ] **BEAST MODE** hey, it works!

**Comment by pcreglow** [comment]
Result of `add`-ing empty directories and trying to commit:

```
nothing added to commit 

Already up-to-date!
```

Researching this  issue a little more, the [Git index](https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F) only allows files to be listed. Thanks to a tip from @sjoyal and reading this [explanation](http://stackoverflow.com/questions/8281322/uploading-a-empty-folder-to-github) on StackOverflow, I was able to add, commit the directories and required files with `touch <file>` on the command line.

**Comment by pcreglow** [comment]
pcreglow.github.io:journal-week-1 PR

https://github.com/pcreglow/pcreglow.github.io/pull/6

**Comment by pcreglow** [comment]
TIY-Assignments:05--monday-review+preview PR

https://github.com/pcreglow/TIY-Assignments/pull/9

**Comment by al-the-x** [comment]
Hey, what about that PR in `student-roster`?

**Comment by pcreglow** [comment]
TheIronYard-Orlando/student-roster PR:

https://github.com/TheIronYard--Orlando/student-roster/pull/18

**Comment by al-the-x** [comment]
Please review and close.
