### ISSUE TITLE
05 -- Monday Review & Preview -- Michael Staehling

### ISSUE THREAD

**Issue by MStaehling** [TheIronYard--Orlando/2015--SUMMER--FEE#76]
- [ ] **Yak Shaving**
  - _WIP Issue_: `05 -- Monday Review & Preview -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
    - [x] link to PR for `TIY-Assignments:05--monday-review+preview`
  -  _WIP Branch_:
    - `USERNAME.github.io:journal-week-1`
    - `TheIronYard--Orlando/student-roster:master`
    - `TIY-Assignments:05--monday-review+preview`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/jquery.md`
      - `journal-week-1.md`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/FEE/`
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `FullWidthTabs/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `QuotesRotator/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
- [ ] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [ ] added draft journal entry
- [ ] **GitHubbing to Know You, Part 2** (due Thu)
  - [ ] merged upstream additions from `TheIronYard/student-roster:master`
  - [ ] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"
- [ ] **Making Blueprints**
  - [x] created branch in `TIY-Assignments` named `05--monday-review+preview`
  - [x] created directories named `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
  - [x] pasted result of `add`-ing empty directories into _WIP Issue_
  - [x] added files: `index.html`, `styles.css`, `scripts.js`
  - [x] copied contents of `index.html` and `styles.css` from examples
  - [ ] **BEAST MODE** working code in the browser!
- [ ] **Prep for TodoMVC**
  - [x] downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template)
  - [x] pushed into `TIY-TodoMVC`
  - [ ] **BEAST MODE** hey, it works!

```

### Journal, Week 1

You've just completed your first week at The Iron Yard. You've learned a lot in a very short amount of time. Take some time tonight to review your notes and write them down. Use whatever format helps you get the ideas out: bulleted lists, stream of consciousness, retelling a story. Consider this a draft that you'll revise a few times throughout the week. Put this work in a branch called `journal-week-1` in your `USERNAME.github.io` repo. Don't forget to link to that PR in your _WIP Issue_! Here are some suggestions for topics:

* What do developers do? What principles of a developer have you learned?
* Explain the outside-in and inside-out technique we employed for TodoCLI.
* Describe the technique of using User Stories to write application specifications.
* Write something about the principle of Extreme Programming (XP) called YAGNI.

If you're looking to get a leg up on the material for the week, start investigating the DOM and

### GitHubbing to Know You, Part 2

This week, you'll be randomly assigned classmates to interrogate and a question to ask. Then, you get to update _their_ Markdown file in the Student Roster and open a PR for the change. Chances are high (i.e. I rigged it) that the person you get _won't_ get assigned you... fun, right? You'll know all kinds of embarassing details about each other in no time!

### Making Blueprints

Some of your homework assignments for the week will be duplicating functionality based on a [reference implementation](http://en.wikipedia.org/wiki/Reference_implementation).

* Create directories for `NestedAccordion`, `FullWidthTabs`, and `QuotesRotator`
* try `git add` on empty directories: what happens? why do you think? what can you find about it?
* copy example code: HTML into `index.html`, CSS into `styles.css`, JS into `scripts.js`

#### BEAST MODE

If you open the `index.html` files that you just made in a browser you'll run into some problems. Can you fix them so that they work _exactly_ like the demo sites?

### Prep for TodoMVC

Tomorrow, we'll start building [TodoMVC](http://todomvc.com) with plain "vanilla" JavaScript in the browser. To get ready, you'll need to [download the starter template from Github](). Create a new repo on Github called `TIY-TodoMVC` and commit and push the contents of the starter template to `master`. Then review the [application specifications]() and examine some of the reference implementations.

#### BEAST MODE

If you open the `index.html` file from the starter template in a browser, it probably won't look like much. Can you get it working? There's probably a `README` file lying around somewhere that can help you.

## Resources

* [TodoMVC](http://todomvc.com)
  * [starter template on Github](https://github.com/tastejs/todomvc-app-template) ([download](https://github.com/tastejs/todomvc-app-template/archive/master.zip))
  * [project specifications](https://github.com/tastejs/todomvc/blob/master/app-spec.md)
* References for DOM JavaScript
  * [_Document Object Model_ on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model)
  * [_Interactive Web Pages with JavaScript_ on Team Treehouse](http://teamtreehouse.com/library/interactive-web-pages-with-javascript)
  * [_Try jQuery_ on Code School](https://www.codeschool.com/courses/try-jquery)
* [_Blueprints_ articles on Tympanus.net](http://tympanus.net/codrops/category/blueprints/)
  * [Nested Accordion](http://tympanus.net/Blueprints/NestedAccordion/)
  * [Full Width Tabs](http://tympanus.net/Blueprints/FullWidthTabs/)
  * [Quotes Rotator](http://tympanus.net/Blueprints/QuotesRotator/)
```

**Comment by MStaehling** [comment]
https://github.com/MStaehling/MStaehling.github.io/pull/3

**Comment by MStaehling** [comment]
https://github.com/TheIronYard--Orlando/student-roster

https://github.com/TheIronYard--Orlando/student-roster/blob/master/2015-05/FEE/MStaehling.md

**Comment by MStaehling** [comment]
git add nestedaccordion
fatal: pathspec 'nestedaccordion' did not match any files
-> [128]

????

**Comment by al-the-x** [comment]
No links to your PRs. Let's talk.

**Comment by al-the-x** [comment]
Also, please include _only_ the checklist in your description.

**Comment by al-the-x** [comment]
Please review and close.

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-assignments/pull/11
